### ISSUE TITLE
The viewing session is not available or has expired.

### ISSUE THREAD

**Issue by bharath1206** [eclipse-birt/birt#1026]
I am getting an error when trying to access multiple BIRT reports,  Accessed the first report after login the application and it loads correctly, then I tried to access another report getting an error with an Exception popup and message on it as "The viewing session is not available or has expired." 

Appreciate your reply. TIA.

![birt_error](https://user-images.githubusercontent.com/7869505/182696183-e2467b15-db8f-47a1-b9e9-0864b461c6e8.jpg)

**Comment by vpease** [comment]
i have published a pr to solve this.
#1233
The problem is that the ajax call is sending the "Connection" Header. 

Just avoid sending the Connection header solves the problem

**Comment by speckyspooky** [comment]
The issue is fixed with PR #1233
