### ISSUE TITLE
Birt runtime.jar has embedded many 3rd party libs

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [eclipse-birt/birt#1094]
org.eclipse.birt.runtime_4.10.0-20221001.jar has embedded:
- Apache Commons lang
- slf4j
- W3C Tidy
- Apache Cassandra
- and many others

This makes it easy to have clashes with other dependencies.

![image](https://user-images.githubusercontent.com/6008104/198044374-59311254-e958-487f-bb28-3f2f3afd57e5.png)

**Comment by hvbtup** [comment]
I'm explicitly not an expert here, but...

The idea of the BIRT runtime distribution is to have every dependency included, in a combination that actually works.

You can consider using the OSGI runtime. OSGI promises to solve such compatibility issues (just like modularization in never Java versions), allowing you to use different releases of the same library in different parts of your program.

You can also consider running BIRT in a separate process (e.g. use Tomcat with the BIRT viewer and use BIRT's HTTP API to run reports).

**Comment by speckyspooky** [comment]
Many of the listed libraries are excluded with the latest built like Cassandra, slf4j, guava, hector.
Tidy is updated to a new version.
