### ISSUE TITLE
Properties window is blank for flat-file datasource

### ISSUE THREAD

**Issue by alex-berezin** [eclipse-birt/birt#1117]
Dear team,

Please help with resolving the following issue:

When opening the properties of the flat file datasource there is nothing displayed but blank window. 
There is also no options available when configuring dataset based on flat file datasource. 
This is on MacOS, on Windows everything is fine. 

<img width="808" alt="image" src="https://user-images.githubusercontent.com/19150982/204118735-393c88a8-b0fa-495a-9af9-6c1688302f74.png">
<img width="803" alt="image" src="https://user-images.githubusercontent.com/19150982/204118748-bdc5cd01-5ff2-446a-a7d6-3ccd4a6c356a.png">

**Comment by wimjongman** [comment]
Please attach eclipse logs.

**Comment by alex-berezin** [comment]
Hi Wim,

Thanks a lot for reaching out.
[Untitled.log](https://github.com/eclipse/birt/files/10100660/Untitled.log)

Attached is the error log from Eclispse.

**Comment by alex-berezin** [comment]
I was wrong, bug actually appears in the Windows version as well when installing via "Install New Software" from Eclipse.

**Comment by wimjongman** [comment]
Please test with the current milestone.

https://download.eclipse.org/birt/updates/milestone/latest/index.html

**Comment by speckyspooky** [comment]
Currently there is no response whether the hint from Wim was tested and what the result is.
(If I use the all-in-one-designer for Windows all is fine. Not tested the eclipse update way.)

The installation options for eclipse are improved - see #1885.
If there are problems again let us know and we can reopen the issue ticket.
