### ISSUE TITLE
Unable to produce PDF reports with OSGI due to Unresolved requirement

### ISSUE THREAD

**Issue by emassino** [eclipse-birt/birt#1225]
Hello PDF cannot be created using osgi with BIRT 4.12.0-20221128 due to conflict with  javax.annotation generated by com.github.librepdf.openpdf.jar. See attached log. We solved it changing the MANIFEST in the com.github.librepdf.openpdf.jar removing  javax.annotation from the Export-Package and Import-Package.
[osgi.txt](https://github.com/eclipse/birt/files/10879270/osgi.txt)
[MANIFEST.txt](https://github.com/eclipse/birt/files/10879289/MANIFEST.txt)

**Comment by speckyspooky** [comment]
Please try the latest release BIRT 4.13 [https://download.eclipse.org/birt/downloads/drops/R-R1-4.13.0-202303022006/](url) and verify the PDF creation. The tests of both BIRT versions from my side are fine with PDF.

**Comment by speckyspooky** [comment]
You are able to test the latest 4.13-OSGI-version? Did you get the PDF-output correctly?

**Comment by speckyspooky** [comment]
The problem is solved with the latest BIRT 4.14.0 versions.
