### ISSUE TITLE
Bundle-ClassPath entry does not exist

### ISSUE THREAD

**Issue by rgra** [eclipse-birt/birt#1277]
In my maven tycho build with BIRT 4.13 in the target platform I get a lot of warnings "Bundle-ClassPath entry does not exist".

Is it possible to fix those?

[WARNING] Bundle-ClassPath entry enginetesthelper.jar does not exist in C:\temp\maven3\p2\osgi\bundle\org.eclipse.birt.report.engine\4.13.0.v202303021806\org.eclipse.birt.report.engine-4.13.0.v202303021806.jar
[WARNING] Bundle-ClassPath entry tests.jar does not exist in C:\temp\maven3\p2\osgi\bundle\org.eclipse.birt.report.model\4.13.0.v202303021806\org.eclipse.birt.report.model-4.13.0.v202303021806.jar
[WARNING] Bundle-ClassPath entry modelFragment_internal.jar does not exist in C:\temp\maven3\p2\osgi\bundle\org.eclipse.birt.report.model\4.13.0.v202303021806\org.eclipse.birt.report.model-4.13.0.v202303021806.jar
[WARNING] Bundle-ClassPath entry library.jar does not exist in C:\temp\maven3\p2\osgi\bundle\org.eclipse.birt.data\4.13.0.v202303021806\org.eclipse.birt.data-4.13.0.v202303021806.jar
[WARNING] Bundle-ClassPath entry library.jar does not exist in C:\temp\maven3\p2\osgi\bundle\org.eclipse.birt.report.data.adapter\4.13.0.v202303021806\org.eclipse.birt.report.data.adapter-4.13.0.v202303021806.jar
[WARNING] Bundle-ClassPath entry library.jar does not exist in C:\temp\maven3\p2\osgi\bundle\org.eclipse.birt.report.engine.emitter.pdf\4.13.0.v202303021806\org.eclipse.birt.report.engine.emitter.pdf-4.13.0.v202303021806.jar
[WARNING] Bundle-ClassPath entry derby.jar does not exist in C:\temp\maven3\p2\osgi\bundle\org.eclipse.birt.report.data.oda.jdbc\4.13.0.v202303021806\org.eclipse.birt.report.data.oda.jdbc-4.13.0.v202303021806.jar

**Comment by merks** [comment]
I believe this is fixed by this recent change:

https://github.com/eclipse-birt/birt/pull/1779
