### ISSUE TITLE
Website is not available

### ISSUE THREAD

**Issue by Deilan** [eclipse-birt/birt#1289]
1. Go to https://eclipse.github.io/
2. Be automatically redirected to https://eclipse.github.io/birt-website/
3. Get 404 Page Not Found

![image](https://github.com/eclipse-birt/birt/assets/4777512/49e23390-b347-4071-b8b3-9fda14bbb724)

**Comment by wimjongman** [comment]
Thanks, Michael. This issue is caused by our recent move. It is tracked here: https://github.com/eclipse-birt/birt-website/issues/56
