### ISSUE TITLE
Main build fails

### ISSUE THREAD

**Issue by wimjongman** [eclipse-birt/birt#1292]
https://github.com/eclipse-birt/birt/pull/1291 caused the main build to fail.

https://ci.eclipse.org/birt/job/birt-master/286/console

**Comment by wimjongman** [comment]
I bumped the build to use latest lts.

**Comment by merks** [comment]
@wimjongman 

I guess this can be closed now because the builds are working:

https://ci.eclipse.org/birt/job/birt-master/
