### ISSUE TITLE
BIRT-viewer not runable - HTTP ERROR 500 javax.servlet.ServletException: org.apache.jasper.JasperException - latest branch version and snapshot version => 4.13.0-20230531

### ISSUE THREAD

**Issue by speckyspooky** [eclipse-birt/birt#1301]
Hello Together,
I figured out that we have an issue with the latest BIRT-version.
**The effect is that the BIRT-viewer couldn't be started so we haven't currently a runable BIRT-preview.**

Involved:
- The error is reproduceable with the latest BIRT-version, Snapshot: 4.13.0-20230531
- The error is also reproducable with our latest repository sources.
- The direct call of emitters (HTML, PDF, etc. works correctly.)

There seems to be an issue with dependencies. Both error messages show the root:
**java.lang.ClassNotFoundException: com.sun.el.ExpressionFactoryImpl cannot be found by org.eclipse.jetty.osgi.boot_10.0.15**

Here the error messages from development-environment & BIRT-snapshot-version:

### BIRT-viewer from my development eclipse started:

HTTP ERROR 500 javax.servlet.ServletException: org.apache.jasper.JasperException: javax.servlet.ServletException: javax.el.ELException: Provider com.sun.el.ExpressionFactoryImpl not found
URI:	/viewer/frameset
STATUS:	500
MESSAGE:	javax.servlet.ServletException: org.apache.jasper.JasperException: javax.servlet.ServletException: javax.el.ELException: Provider com.sun.el.ExpressionFactoryImpl not found
SERVLET:	ViewerServlet
CAUSED BY:	javax.servlet.ServletException: org.apache.jasper.JasperException: javax.servlet.ServletException: javax.el.ELException: Provider com.sun.el.ExpressionFactoryImpl not found
CAUSED BY:	org.apache.jasper.JasperException: javax.servlet.ServletException: javax.el.ELException: Provider com.sun.el.ExpressionFactoryImpl not found
CAUSED BY:	javax.servlet.ServletException: javax.el.ELException: Provider com.sun.el.ExpressionFactoryImpl not found
CAUSED BY:	javax.el.ELException: Provider com.sun.el.ExpressionFactoryImpl not found
CAUSED BY:	java.lang.ClassNotFoundException: com.sun.el.ExpressionFactoryImpl cannot be found by org.eclipse.jetty.osgi.boot_10.0.15
Caused by:

javax.servlet.ServletException: org.apache.jasper.JasperException: javax.servlet.ServletException: javax.el.ELException: Provider com.sun.el.ExpressionFactoryImpl not found
![eclipse-BIRT-viewer](https://github.com/eclipse-birt/birt/assets/41593722/c145ba3f-abc8-4a96-8716-4ca7c0159afb)

### BIRT-viewer from Snapshot 20230531 BIRT-all-in-one-designer:

HTTP ERROR 500 javax.servlet.ServletException: org.apache.jasper.JasperException: org.apache.jasper.JasperException: Unable to compile class for JSP
URI:	/viewer/frameset
STATUS:	500
MESSAGE:	javax.servlet.ServletException: org.apache.jasper.JasperException: org.apache.jasper.JasperException: Unable to compile class for JSP
SERVLET:	ViewerServlet
CAUSED BY:	javax.servlet.ServletException: org.apache.jasper.JasperException: org.apache.jasper.JasperException: Unable to compile class for JSP
CAUSED BY:	org.apache.jasper.JasperException: org.apache.jasper.JasperException: Unable to compile class for JSP
CAUSED BY:	org.apache.jasper.JasperException: Unable to compile class for JSP
CAUSED BY:	javax.el.ELException: Provider com.sun.el.ExpressionFactoryImpl not found
CAUSED BY:	java.lang.ClassNotFoundException: com.sun.el.ExpressionFactoryImpl cannot be found by org.eclipse.jetty.osgi.boot_10.0.15
Caused by:

javax.servlet.ServletException: org.apache.jasper.JasperException: org.apache.jasper.JasperException: Unable to compile class for JSP

![birt-all-in-one-designer-20230531-birt-viewer](https://github.com/eclipse-birt/birt/assets/41593722/92dec753-2484-4585-9f9e-c1711ff8df98)

Full stack trace:
[http-error-500-stack-trace.txt](https://github.com/eclipse-birt/birt/files/11643154/http-error-500-stack-trace.txt)

**Comment by merks** [comment]
Could you describe how to reproduce the problem? I assume that no existing test covers this case…

**Comment by speckyspooky** [comment]
The first way:
download the snapshot version from our download folder and start directly a simple report with the "run" / "play" button.

The second way:
I created a complet new branch with the master sources - start "all-in-one" - start a simple report.

Screen of case 1:

![play-button](https://github.com/eclipse-birt/birt/assets/41593722/186e7fc7-f674-4efa-a7b6-06eeb0508c51)

**Comment by merks** [comment]
I get this far but I don't know how to do even the simplest thing here:

![image](https://github.com/eclipse-birt/birt/assets/208716/c92626e2-d43d-4144-a137-6ab47848dcfa)

Is there some "sample" report thing that I can try?  It would be good to assume that I know nothing and that I am somewhat stupid, so I need the baby steps to get to the point of seeing problem so that I can determine which bundle is needed for that dependency...

**Comment by speckyspooky** [comment]
You have started already the all-in-one-designer.

Next step is to change the perspective to "report designer", use the following way:


![BIRT-perspective-report-designer](https://github.com/eclipse-birt/birt/assets/41593722/91e7c855-08ef-4722-bff6-8e3d702d38d1)


Yes, you can create a simple report on your own or you can use my example for background-images (one of my standard test reports):
[background_image_testcase01_cell_#1255.zip](https://github.com/eclipse-birt/birt/files/11643402/background_image_testcase01_cell_.1255.zip)

**Comment by merks** [comment]
When I hit "play" a webpage came up like this:

![image](https://github.com/eclipse-birt/birt/assets/208716/b5f56272-03ba-4e67-8b65-c0f3ad498124)

I was already tweaking some dependencies before-hand.  Is this working correctly then?  I think adding this dependency solved the problem:

![image](https://github.com/eclipse-birt/birt/assets/208716/521a9da5-48d0-4ac1-b938-28501dc9d7e1)

**Comment by speckyspooky** [comment]
Looks good to me.
Please create a PR for it, so I can test it later from my side too.
