### ISSUE TITLE
Improvement of the BIRT-viewer, small styling renew

### ISSUE THREAD

**Issue by speckyspooky** [eclipse-birt/birt#1307]
Hello together,

I started a very small sensitive improvement of the BIRT-viewer.
Since I started the BIRT usage 2017 I had the same preview with a little bit old fashioned style.

On my one viewer I had updated the coloring, the main function icons and the parameter icons.
Now I wants to push these changes to the BIRT-master.

But before I start a PR here you can see the sensitive styling changes.
There are only changes on coloring and 8 icons (no master renew).

The main change is that I removed the beige-light-brown through a blue color and a very light gray of the dialog.
I know that the most use and own integration and styling can be a very sensitive topic,
but I think it would be good to have small changes after a so long time.

Please let me know your comments - The icons created on my own (no foreign icons).

### Styling compare - Left side "current version"  / Right side "renewed version"

![birt-preview-sensitive-renew](https://github.com/eclipse-birt/birt/assets/41593722/90919d62-cb81-4561-839c-3ca554658d09)

**Comment by hvbtup** [comment]
I like the new look, but OTOH we don't use the viewer in our application, we only see the parameter entry UI during development, when we're running the report from the All-In-One IDE.

**Comment by speckyspooky** [comment]
Same on my side the viewer isn't part my application.
The idea is to get a little bit smarter viewer for the report developer with a little bit modern feeling.

**Comment by speckyspooky** [comment]
The new layout is available with the latest snapshot of BIRT-4-14.
