### ISSUE TITLE
Build is not working

### ISSUE THREAD

**Issue by hvbtup** [eclipse-birt/birt#1315]
As I said in #1313, after merging the latest commits from master into a bugfix branch, I am unable to build.

So I started from scratch:
Install the IDE using the Eclipse installer.
During the installation, assure that the new GIT repo URL is used.
Navigate to the *.target file and "set as target platform".

This fails (with the current master):

![grafik](https://github.com/eclipse-birt/birt/assets/7644776/8f42e22e-261c-4f12-bcdc-5c8af23d074a)

Examples of build error messages:

First error:
API analysis aborted for 'org.eclipse.birt.report.engine.dataextraction' since its build path is incomplete

Second error:
One or more cycles were detected in the build path of project 'extension-tutorial-1'. The paths towards the cycle and cycle are:
extension-tutorial-1->{org.eclipse.birt.report.designer.ui, org.eclipse.birt.report.engine, org.eclipse.birt.report.designer.tests}
extension-tutorial-1->{org.eclipse.birt.report.designer.ui, org.eclipse.birt.report.engine, org.eclipse.birt.report.designer.tests, org.eclipse.birt.report.designer.ui.ide}
extension-tutorial-1->{org.eclipse.birt.report.designer.ui, org.eclipse.birt.report.engine, org.eclipse.birt.report.designer.tests, org.eclipse.birt.report.designer.ui.ide, org.eclipse.birt.report.designer.ui.lib}
extension-tutorial-1->{org.eclipse.birt.report.designer.ui, org.eclipse.birt.report.engine, org.eclipse.birt.report.designer.tests, org.eclipse.birt.report.designer.ui.ide, org.eclipse.birt.report.designer.ui.lib, org.eclipse.birt.report.designer.ui.editors}
extension-tutorial-1, org.eclipse.birt.report.designer.ui->{org.eclipse.birt.report.engine, org.eclipse.birt.report.designer.tests, org.eclipse.birt.report.designer.ui.ide, org.eclipse.birt.report.designer.ui.lib, org.eclipse.birt.report.designer.ui.editors, org.eclipse.birt.report.designer.ui.views}
extension-tutorial-1->{org.eclipse.birt.report.engine, org.eclipse.birt.report.designer.tests, org.eclipse.birt.report.designer.ui.ide, org.eclipse.birt.report.designer.ui.lib, org.eclipse.birt.report.designer.ui.editors, org.eclipse.birt.report.designer.ui.views, org.eclipse.birt.report.engine.nl}
extension-tutorial-1, org.eclipse.birt.report.designer.ui, org.eclipse.birt.report.engine->{org.eclipse.birt.report.designer.tests, org.eclipse.birt.report.designer.ui.ide, org.eclipse.birt.report.designer.ui.lib, org.eclipse.birt.report.designer.ui.editors, org.eclipse.birt.report.designer.ui.views, org.eclipse.birt.report.engine.nl}
extension-tutorial-1->{org.eclipse.birt.report.engine, org.eclipse.birt.report.designer.tests, org.eclipse.birt.report.designer.ui.ide, org.eclipse.birt.report.designer.ui.lib, org.eclipse.birt.report.designer.ui.editors, org.eclipse.birt.report.designer.ui.views, org.eclipse.birt.report.engine.testhelper}
extension-tutorial-1, org.eclipse.birt.report.designer.ui, org.eclipse.birt.report.engine->{org.eclipse.birt.report.designer.tests, org.eclipse.birt.report.designer.ui.ide, org.eclipse.birt.report.designer.ui.lib, org.eclipse.birt.report.designer.ui.editors, org.eclipse.birt.report.designer.ui.views, org.eclipse.birt.report.engine.testhelper}
extension-tutorial-1->{org.eclipse.birt.report.designer.ui, org.eclipse.birt.report.engine, org.eclipse.birt.report.designer.tests, org.eclipse.birt.report.designer.ui.ide, org.eclipse.birt.report.designer.ui.lib, org.eclipse.birt.report.designer.ui.editors, org.eclipse.birt.report.designer.ui.views}
extension-tutorial-1, org.eclipse.birt.report.designer.ui->{org.eclipse.birt.report.engine, org.eclipse.birt.report.designer.tests, org.eclipse.birt.report.designer.ui.ide, org.eclipse.birt.report.designer.ui.lib, org.eclipse.birt.report.designer.ui.editors}
extension-tutorial-1, org.eclipse.birt.report.designer.ui->{org.eclipse.birt.report.engine, org.eclipse.birt.report.designer.tests, org.eclipse.birt.report.designer.ui.ide, org.eclipse.birt.report.designer.ui.lib, org.eclipse.birt.report.designer.ui.editors.schematic}
extension-tutorial-1->{org.eclipse.birt.report.designer.ui, org.eclipse.birt.report.engine, org.eclipse.birt.report.designer.tests, org.eclipse.birt.report.designer.ui.ide, org.eclipse.birt.report.designer.ui.lib, org.eclipse.birt.report.designer.ui.editors.schematic}
extension-tutorial-1->{org.eclipse.birt.report.designer.ui, org.eclipse.birt.report.engine, org.eclipse.birt.report.designer.tests, org.eclipse.birt.report.designer.ui.ide, org.eclipse.birt.report.designer.ui.lib.explorer}
extension-tutorial-1, org.eclipse.birt.report.designer.ui, org.eclipse.birt.report.engine, org.eclipse.birt.report.designer.tests, org.eclipse.birt.report.designer.ui.ide->{org.eclipse.birt.report.designer.ui, org.eclipse.birt.report.engine, org.eclipse.birt.report.designer.tests, org.eclipse.birt.report.designer.ui.ide, org.eclipse.birt.report.designer.ui.lib, org.eclipse.birt.report.designer.ui.editors.schematic, org.eclipse.birt.report.designer.ui.editors}

**Comment by merks** [comment]
Are you using the Oomph setup for your IDE?  It's changed significantly the over the past few weeks.   Y

You are likely best to create a fresh new environment using the setup link:

https://github.com/eclipse-birt/birt#create-a-birt-development-environment

**Comment by hvbtup** [comment]
That's what I did.

**Comment by merks** [comment]
You've tried a Project -> Clean...  to clean all projects?    Sometimes I have one to two maven errors to do mostly with Javadoc things, but I just delete those errors:

![image](https://github.com/eclipse-birt/birt/assets/208716/d7c8b473-b5f2-41e4-9443-444579318fae)

I don't expect an API baseline is set:

![image](https://github.com/eclipse-birt/birt/assets/208716/7d896f30-fd35-4ec0-911b-f99e53b209c0)

I do know that all these projects with m2e natures behave kind of strangely initially.  Initially it spends quite some time setting up the classpath containers:

![image](https://github.com/eclipse-birt/birt/assets/208716/0b95c283-0230-4417-be8b-0154b05a185f)

And then there are some errors that get cleaned up again shortly:

![image](https://github.com/eclipse-birt/birt/assets/208716/243c47b5-6b49-425c-8ed6-281cd4d32eca)

Trying it again right now from scratch it completes like this:

![image](https://github.com/eclipse-birt/birt/assets/208716/07317e61-ba9b-47c5-b4f5-b9cec14314ff)

There's nothing too worrisome in the error log:

![image](https://github.com/eclipse-birt/birt/assets/208716/8b1a3184-ba5d-4bb9-ba26-8adabeb39890)

Can you show more of the errors columns so that I can see what type of error that is?

**Comment by hvbtup** [comment]
Funny thing: Today, when I started Eclipse again, it just worked (without changing anything). A restart of Eclipse yesterday had no effect. I guess some kind of internal cahing mechanism isn't working correctly.

**Comment by merks** [comment]
Very strange.  😞   But I'm glad it's better today!

**Comment by speckyspooky** [comment]
...yes, I can confirm somethimes eclipse has good days and sometimes it tries to think and I got results like Henning.
But with the good end of the new day I will close the issue.
