### ISSUE TITLE
Prepare the index.jsp for 4.14 and renew the styling

### ISSUE THREAD

**Issue by speckyspooky** [eclipse-birt/birt#1329]
The current version of index.jsp-side of the BIRT-viewer should be configured for BIRT 4.14 (support for #1286).
In addition to it the style of the old page will be a little bit modernized.

The new index.jsp will be:

![index jsp](https://github.com/eclipse-birt/birt/assets/41593722/7d1580b7-6efd-4666-a0f1-dd8361042179)

The new example (Hello world reports) will be:

Example report 01:

![report01](https://github.com/eclipse-birt/birt/assets/41593722/a6176ac0-c4d4-49ae-8164-ed8429c19ec8)

Example report 02:

![report02](https://github.com/eclipse-birt/birt/assets/41593722/ef37e7d5-654f-4867-9251-3622c8a5dbed)

**Comment by wimjongman** [comment]
Wunderbar!
