### ISSUE TITLE
Renew web viewer parameter dialog & optional flag of textboxes

### ISSUE THREAD

**Issue by speckyspooky** [eclipse-birt/birt#1346]
The current parameter dialog should get some smaller styling changes of the checkboxes and the radio buttons.
Additional on it the handling of the "optional" radio-buttons will be improved to have only an "null"-checkbox instead to have 2 radio-buttons.

### Current version of the parameter dialog

![old-version](https://github.com/eclipse-birt/birt/assets/41593722/acb9abf4-bde6-4706-9088-60337d147a12)

### Renewd version of the parameter dialog and textbox

![new-version](https://github.com/eclipse-birt/birt/assets/41593722/c0cc9e2c-b883-4415-b79b-0d8bd9ba2094)

**Comment by wimjongman** [comment]
Nice!!!

**Comment by speckyspooky** [comment]
Improvement is part of PR #1329

**Comment by speckyspooky** [comment]
Done with built of birt-runtime-4.14.0-202306261418.
