### ISSUE TITLE
Why is 4.14 runtime much bigger than 4.13?

### ISSUE THREAD

**Issue by hvbtup** [eclipse-birt/birt#1377]
I noticed that the `birt-runtime-*.jar` file generated from the current master (upcoming BIRT 4.14) is much bigger than the corresponding file generated with BIRT 4.13.

I don't understand the build process really, but to me it seems that the folder 
`build\birt-packages\birt-runtime\target\package\ReportEngine\lib` which is the base for generating the ZIP, 
now contains a lot of files which, judging them by their names, seem to be irrelevant for the runtime 
and instead related to the UI only, e.g. files like `org.eclipse.e4.ui.css.core_0.14.100.v20230701-0639.jar`.

Disclaimer: I've seen this in the `tup_main` branch of my fork, but I'm pretty sure this happens with the `master` branch as well.

For this branch, the ReportEngine\lib folder is now about 20 MB bigger with 4.14 than with 4.13.

**Comment by merks** [comment]
This commit added a feature to the product that determines the runtime contents:

https://github.com/eclipse-birt/birt/commit/92c78b3eb97f956808fe42a2c9f22a3016226c10

This describes why:

  https://github.com/eclipse-birt/birt/pull/1342

One would not expect a "runtime" feature to have UI dependencies, but apparently it does.

It could take much work to figure how how to do it differently, i.e, to figure how else to ensure that the runtime is complete without being "over complete by adding missing things to /org.eclipse.birt.engine.runtime/feature.xml until the other feature can be removed from the product without breaking the runtimes.   And I haven't even got the tests that test the runtimes working...

**Comment by hvbtup** [comment]
OK. I hope this doesn't introduce additional security risks.

**Comment by hvbtup** [comment]
I'm fine with the status ATM. 
However, regarding "not bundles that won't be activated anyway": Maybe you and me know this (more or less), but some of our clients regurlarly scan the disks for DLLs/JARs with known security issues. Copying files which are not really necessary increases the risk of false positives, and then one has to discuss them with the clients IT security department again and again.

**Comment by merks** [comment]
Indeed, I recall the log4j debacle.   That being said, I assume clients have budgets and such clients might collectively consider investing a very small portion of their budget on defense/BIRT...

**Comment by speckyspooky** [comment]
During the cleanup steps in the mean time the size will be reduced a little bit.
And during the given answer that we need the solution currently, I will close the issue.
