### ISSUE TITLE
Font aliasing not working for HTML text

### ISSUE THREAD

**Issue by hvbtup** [eclipse-birt/birt#1385]
This isn't a new issue, but it's a serious blocker for migrating from running BIRT on Windows to running BIRT on Linux:

The font aliasing specified in fontConfig.xml does not work for HTML font attributes.

I'll try to explain this in detail:

The attached report output should show the text in the same style twice, but the second output using the builtin Times-Roman font instead of a subsetted Arial TrueType font as expected.

[20230802-3134388.pdf](https://github.com/eclipse-birt/birt/files/12239658/20230802-3134388.pdf)

This output was created from a report where I specify font name, size etc. as report parameters and then use different ways to dynamically generate formatted text:

![grafik](https://github.com/eclipse-birt/birt/assets/7644776/15942895-33bc-45ad-a244-28f5717c0c1b)

onCreate event of the first item (row["TEXT"):

    this.getStyle().fontFamily = row["SCHRIFTART"];
    if (row["FETT"] == "J") this.getStyle().fontWeight = "bold";
    if (row["KURSIV"] == "J") this.getStyle().fontStyle = "italic";
    this.getStyle().fontSize = row["GROESSE"];

HTML source of the second item:

    "<span style='font-family:" + row["SCHRIFTART"] + (row["FETT"]=="J"? "; font-weight:bold" : "") + (row["KURSIV"]=="J"? "; font-style:italic" : "") + "; font-size:" + row["GROESSE"] + "'>" + row["TEXT"] + "</span>"

BIRT is running on Linux (in a Podman container, to be precise), with no Arial TrueType font available, but we have Liberation Sans available:
![grafik](https://github.com/eclipse-birt/birt/assets/7644776/e6abbbae-1b01-40df-a699-27e3c3da9daf)
And we have defined font aliasing in the `fontConfig.xml` file:

    ...
	<font-aliases>
		<mapping name="serif" font-family="Times-Roman" />
		<mapping name="sans-serif" font-family="Helvetica" />
		<mapping name="monospace" font-family="Courier" />
		<mapping name="cursive" font-family="Times-Roman" />
		<mapping name="fantasy" font-family="Times-Roman" />
		<mapping name="Arial Narrow" font-family="Liberation Sans Narrow" />
		<mapping name="Arial Black" font-family="Roboto Black" />
		<mapping name="Arial" font-family="Liberation Sans" />
		<mapping name="Times New Roman" font-family="Liberation Serif" />
		<mapping name="Courier New" font-family="Liberation Mono" />
	</font-aliases>
    ...
	<font-paths>
		
		<path path="/app/reporting/fonts" />
		
		<path path="/app/config/birt" />
    ...

The font aliasing is working for statically formatted items and it's working when we set BIRT CSS style properties dynamically,
but it is *not working for styling using the HTML style attribute* `style='font-family:"Arial"'`.

A little background:

On MS Windows, using the Arial font for subsetting it into PDFs is not a problem, because it's usually part of Windows anyway, and the license allows it.

On other OSes like Linux, Arial is not preinstalled, and I'm not sure if it ok to just copy the *.ttf files from a Windows machine.
The Liberation Sans font is designed in such a way that it can be used as a good replacement (not looking exactly the same, but the same metrics).
The reports have originally be designed on and for MS Windows, thus every single report uses the Arial font.
Now I want to let BIRT run on Linux (in a Podman virtualization).

That's why I need the font aliasing.

Some of the reports show HTML formatted text which is stored in database column.
These texts sometimes contain `style='font-family:"Arial"'` HTML attributes, because our users are used to use Arial and don't think about possible licensing issues.

**So what I basically need is the font aliasing working for HTML font-family CSS attributes as well.**

I'm not sure if we can call this a bug, though, because that's only what I'd need for our application in this situation.

Others might say that using HTML style attributes for selecting the font is very different, because the font aliasing was meant to design a report *here* and let it run *there* (in a different environment), and it should look the same if possible, whereas HTML text containing HTML CSS font-family is specified on a different level and the current behavior is more browser-like.

The possible workarounds I see for our application are:

a) update the existing data once, replacing the HTML CSS font-family attributes according to our aliasing map, and change the editor UI, replacing "Alias with "Liberation Sans" in the drop-down list of fonts.
b) Modify the *.rptdesign files etc, basically doint the first part of a) on the fly before handing the text over to the dynamic text item.

Anyway, it would be nice if we could opt-in for using the font-aliasing map for rendering HTML CSS font-family, too.

**Comment by speckyspooky** [comment]
I understand your requirement. And by default it is the same kind of request to support other CCS-attributes which are coming from Text-element and the CSS-styling should be transferred to HTML and PDF.
This will needs changes on the emitter-level for HTML, PDF and so on.

Yes, you described it, this wasn't the orign target of the engine. So it is no bug it is a feature request.
But I understand you well. There are also other CSS-styles which would be very heplful.

So it make sence to keep this topic open till we have time to check it for implementation.

**Comment by speckyspooky** [comment]
@hvbtup 
Hello Henning, I investigated a little bit on your topic and may be there is a way which you could use without a change of BIRT.
I don't know why I didn't remember on it directly but you use the BIRT element "Dynamic Text".
If you would use the element "Text" with the attributes "Dynamic Text" and Text-Interpretation "HTML" it will work without any changes of BIRT.

I have done s small test report based on your logic and the CSS-styles will be added also on PDF.

### Result of Text (HTML)
![text-with-css-styling](https://github.com/eclipse-birt/birt/assets/41593722/133ef92c-2a12-4b35-b2d9-e033482df5a4)

### Text-element with dynamic layout information from data set
![2023-09-24 17_27_30-runtime-birt-all-in-one - C__Users_gutma_Documents_Entwicklung_2_BIRT_report_dev](https://github.com/eclipse-birt/birt/assets/41593722/2a151df0-345f-4161-9546-e27b18c73e19)

### Demo report & generated PDF
[text-with-css-styling.zip](https://github.com/eclipse-birt/birt/files/12708897/text-with-css-styling.zip)

**Comment by hvbtup** [comment]
HTML span styling does work with dynamic text items, too.

The issue at hand is that font substitution as defined in using `fontConfig.xml` is not working.

You can only see this if your runtime environment is different from your development environment,
because inside the development environment you can only choose fonts that *are* available anyway.

But availability may not be given at runtime (in my example, Arial is missing on Linux), so that's when font substitution steps in.

**Comment by speckyspooky** [comment]
I understand your issue of that based on Linux.

So I tested it in another combination. I used "Helvetica" on my report because this font isn't installed on my (Windows-)server.
The span-tag used the style-attribute "font-family:Arial;". The result was like yours that "Times-Roman" was used.
Next step, I added the font-mapping into ***fontConfig.xml*** with the following line:

```
<mapping name="Helvetica" font-family="Arial" />
```

But the mapping wasn't used. I started a debug research of the code where the CSS-attributes will be fetched.
The result was that the Mapping name must be "lower" instead of "normal"/"UpperCamelCase" notation.
(The font-family-attribute is fine.)
My retest with the following mapping was successfull on my pdf-result:

```
<mapping name="helvetica" font-family="Arial" />
```

Could you try please the same configuration with lower case:
```
	<mapping name="arial narrow" font-family="Liberation Sans Narrow" />
	<mapping name="arial black" font-family="Roboto Black" />
	<mapping name="arial" font-family="Liberation Sans" />
	<mapping name="times new roman" font-family="Liberation Serif" />
	<mapping name="courier new" font-family="Liberation Mono" />
```

Here you will get 2 screen of the debugged raw text and the created font-name value in lower case:

![rawValue](https://github.com/eclipse-birt/birt/assets/41593722/48329b37-3b9a-420a-8811-efbf22b2fe86)

![css-value](https://github.com/eclipse-birt/birt/assets/41593722/37497dac-1131-4777-bb31-2ae4eefa9d7f)

**Comment by hvbtup** [comment]
Thanks, Thomas, that is an excellent hint!

I haven't yet tested, but I I think I know where the lower-casing happens (and it is probably OK there, I don't know the CSS specification well enough, but probably the values are meant to be case-insensitive):

![grafik](https://github.com/eclipse-birt/birt/assets/7644776/c7b022f6-6b93-43d1-a591-d852728c6d47)

So I think a possible workaround would be to modify the `fontConfig.xml`.

OTOH wouldn't it make sense to make the font-searching case-insensitive generally? What do you think?

**Comment by hvbtup** [comment]
I tested a report which contains a HTML dynamic text item.
Inside the report definition, the item is defined to use the Arial font (statically).

The HTML text is like this:

    Die Probenentnahme erfolgte durch oder auf Veranlassung des Einsenders.
    <span style="font-family: arial,helvetica,sans-serif;">Die zweite Zeile ist dynamisch als Arial formatiert,<b> zum Teil fett.</b></span>

With my previous `fontConfig.xml` (excerpt)

        <font-aliases>
                <mapping name="serif" font-family="Times-Roman" />
                <mapping name="sans-serif" font-family="Helvetica" />
                <mapping name="monospace" font-family="Courier" />
                <mapping name="cursive" font-family="Times-Roman" />
                <mapping name="fantasy" font-family="Times-Roman" />
                <mapping name="Arial Narrow" font-family="Liberation Sans Narrow" />
                <mapping name="Arial Black" font-family="Roboto Black" />
                <mapping name="Arial" font-family="Liberation Sans" />
                <mapping name="Times New Roman" font-family="Liberation Serif" />
                <mapping name="Courier New" font-family="Liberation Mono" />
        </font-aliases>

this results in this output:

![grafik](https://github.com/eclipse-birt/birt/assets/7644776/37475796-c6ad-45fd-bbf5-7aa57c433af2)

Once I added a line 

    <mapping name="arial" font-family="Liberation Sans" />

the output is now as I want:

![grafik](https://github.com/eclipse-birt/birt/assets/7644776/d88c9008-23ea-4b25-a831-0768dfa81b36)

So using all-lowercase font names in the font-aliases section is a reasonable workaround, thank you very much for your investigation!

**Comment by speckyspooky** [comment]
According to your note, I would confirm your suggestion to have synchronised behavior between
the CSS-font-name and the alias-name handling.
The current implementation is a little bit "special" because you can use the font-name in uppercase or mixed case
nd it will be transferred to "lowercase" for compare. But the alias-font-names (of the mapping configuration) won't be changed to lowercase for compare.

My suggestion would be to solve this "dilemma" is to change the alias names at the HashMap of the font-aliases to lowercase to. (The tests on my side was successful.)

If you confirm that I would create a new PR for it.

### Suggestion of change: FontMappingConfig - change "addFontAlias()":

```
	/** The font-family replacement */
	public void addFontAlias(String alias, String fontName) {
		fontAliases.put(alias.toLowerCase(), fontName);
	}
```
 
![font-aliases](https://github.com/eclipse-birt/birt/assets/41593722/a0a1c75a-b8a9-4f0e-93e3-a92e32b62a96)

**Comment by hvbtup** [comment]
Yes, please create a PR for this. I can hardly imagine that anyone wants do distinguish a font "FancyName" from "FancyName".
However, we will have to test this thoroughly. I can certainly help with testing.

**Comment by speckyspooky** [comment]
@hvbtup 
I will create a PR for that. In my opinion I would prefer that this change will be done after our final version of BIRT 4.14.
It is a small change but it could have hidden side effects, so it would be important that we have enough time for testing.

Do you agree with that implementation plan?

**Comment by hvbtup** [comment]
Yes, +1 for doing this after 4.14
