### ISSUE TITLE
Github action: built-process can be stopped due to missing disk space

### ISSUE THREAD

**Issue by speckyspooky** [eclipse-birt/birt#1425]
The built-process can be stopped due to missing disk space on server side.
So a clean up sequence should be added at ci.yml like github action to clean up cached data.

### Error Screen
![built-no-space-left-on-device](https://github.com/eclipse-birt/birt/assets/41593722/f10d959c-69ec-40a9-8c04-39c4fbd8bbb9)

### Documentation: eclipse helpdesk
https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3692

https://github.com/actions/runner-images/issues/2840

https://github.com/orgs/community/discussions/26351

**Comment by speckyspooky** [comment]
The change is added at PR #1426

**Comment by speckyspooky** [comment]
Change merged to the master.

**Comment by merks** [comment]
Great job 👏🏿
