### ISSUE TITLE
Charts - inconsistent line thickness when imageDPI > 72

### ISSUE THREAD

**Issue by NicolasPerritaz** [eclipse-birt/birt#1428]
The state of the singleton class [Generator ](https://github.com/eclipse-birt/birt/blob/d72d5fb662e98279b560b4fd90acd4164e400907/chart/org.eclipse.birt.chart.engine/src/org/eclipse/birt/chart/factory/Generator.java#L117) is changed in its [render](https://github.com/eclipse-birt/birt/blob/d72d5fb662e98279b560b4fd90acd4164e400907/chart/org.eclipse.birt.chart.engine/src/org/eclipse/birt/chart/factory/Generator.java#L1022) method : 
`fScaleUpdated = true;`

As a result, when we have several charts in a report with `imageDPI ` set to a value higher than 72, the line thickness is adapted only for the first rendered Chart.

This is a side effect of #1155

**Comment by speckyspooky** [comment]
Could you provide a small example report of that issue perhaps with a screen.
It would be help me to understand the problem better and mybe I can debug the behavior there.

**Comment by NicolasPerritaz** [comment]
Thanks @speckyspooky 

I've created a simple example with 2 charts. The 2nd one is just a copy of the 1st, without any changes: [birt-issue-1428.zip](https://github.com/eclipse-birt/birt/files/12788712/birt-issue-1428.zip)

I've set the imageDPI to 300:
![image](https://github.com/eclipse-birt/birt/assets/90317691/b632bb37-5e34-4562-8db2-a742d761c114)

When generating the report using the engine the 2nd chart has thinner gridlines:
![image](https://github.com/eclipse-birt/birt/assets/90317691/452a7805-c4e0-4ba9-b2fc-66ffbaf2d11a)

This issue happens with any output format, but I can't reproduce it from the viewer. It happens only when generating with the engine.

I've tried to debug it and the key is the change in the [Generator's render](https://github.com/eclipse-birt/birt/blob/d72d5fb662e98279b560b4fd90acd4164e400907/chart/org.eclipse.birt.chart.engine/src/org/eclipse/birt/chart/factory/Generator.java#L1022) method. I could see clearly that the 2nd time it is executed (ie for the 2nd chart) the call to [updateDeviceScale method](https://github.com/eclipse-birt/birt/blob/d72d5fb662e98279b560b4fd90acd4164e400907/chart/org.eclipse.birt.chart.engine/src/org/eclipse/birt/chart/factory/Generator.java#L1023C7-L1023C7) is not made because the state has been changed during the 1st call.

The problem is that this behaviour was solving another issue ([#1155](https://github.com/eclipse-birt/birt/pull/1155)), so this has to be taken into consideration.

**Comment by speckyspooky** [comment]
@wimjongman 
Hello Wim, I reviewed your change and tried some test with different options to fix the situation.
But I stuck in without a final solution.

The problem is that your change is working on the generator which is instanciated 1times and so your flag is working for the 1st scaling. Which is exactly what you needed for your issue to avoid scaling more and more.

If a report has more charts then the 1st chart will be scalled but no further chart because the flag is set on the generator instance. I tried to register the scaled charts to identify the scaled charts. But each chart is in every call of the according method an own object instance and so I have no repeatable identifier (same chart, but in all cases a new instance).

So I haven't a good idea to combine the common generator-instance and the recognition of the charts to avoid multiple scale.

Do you have an idea to handle it?

Thanks in advance!

**Comment by speckyspooky** [comment]
@wimjongman Do you have an idea for that?

**Comment by claesrosell** [comment]
I think that the best short-term solution to this is to move the updateDeviceScale(cm, scale) method to the GeneratedChartState class and have the fScaleUpdated state kept there as well.
render would then do : gcs.updateDeviceScale(scale)  instead.

 I can provide a PR for such a solution later today if you want.

**Comment by claesrosell** [comment]
... on a second thought GeneratedChartState is designed to be "immutable" (even if the chart elements are not) to create a method that changes that would be ugly. I need to think more about this.

**Comment by speckyspooky** [comment]
Of course, this is the problem that we have 2 different situations where the old version and the current version works but not at the same time together.

The really stuped thing is that there is no kind of object registry of the renered charts. I tried that to know which chart was scaled for an report but the objects instanziated completely new which is ok, but there is no unique identifier of each chart like "id" or "uuid" (this wouldn't be the best, but we would have a way to solve it).

**Comment by claesrosell** [comment]
Quick and dirty : We could create a copy of the ChartModel and use the copy on all places in the render method.
```
Chart copyOfCharModel = EcoreUtil.copy(cm); 
...
updateDeviceScale(copyOfCharModel, scale);
```
In the test report that added 1ms to the rendering on my computer.

**Comment by speckyspooky** [comment]
Yes, we can give it a try!
