### ISSUE TITLE
org.eclipse.birt.promote fails on master builds after move to Tycho 4.0.3

### ISSUE THREAD

**Issue by claesrosell** [eclipse-birt/birt#1470]
https://ci.eclipse.org/birt/job/build/job/master/52/
I guess this was missed since promote is not done on non master builds?
Since we switched to Tycho 4.0.3 the default file extension has changed to tar.gz for Linux and Mac product archives (https://github.com/eclipse-tycho/tycho/issues/913)

**Comment by merks** [comment]
You're awesome!  🥇
