### ISSUE TITLE
BIRT 4.14 Release Review

### ISSUE THREAD

**Issue by wimjongman** [eclipse-birt/birt#1478]
We will use this issue to track actions concerning the release review.

https://projects.eclipse.org/projects/technology.birt/reviews/4.14.0-release-review

**Comment by waynebeaton** [comment]
Connect with the EMO to initiate the review (there's a link at the top of the page). EMO will guide you through the process.

**Comment by wimjongman** [comment]
The release review is here: https://gitlab.eclipse.org/eclipsefdn/emo-team/emo/-/issues/618

**Comment by wimjongman** [comment]
The release review is finished. We are good to release. 🎉

**Comment by merks** [comment]
FYI, I need to investigate the impact of all the M3 changes, particular WTP which has updated many of its dependencies.

**Comment by wimjongman** [comment]
Yes, I will wait for you. Is there anything I can do here?

**Comment by merks** [comment]
Not yet.  Although I recall I did a test to see which features will all install in SimRel and I concluded some of the runtime features were not intended to install (and could not install).   Could you please have a look at the categorized features and let me know which ones are intended to be installed?

**Comment by wimjongman** [comment]
We install this from marketplace:

* org.eclipse.birt.cshelp
* org.eclipse.birt.doc
* org.eclipse.birt.integration.wtp
* org.eclipse.birt.report.designer.editor.xml.wtp
* org.eclipse.birt
* org.eclipse.birt.chart.cshelp
* org.eclipse.birt.chart.integration.wtp
* org.eclipse.birt.chart

![image](https://github.com/eclipse-birt/birt/assets/180969/a158d8c8-3aa6-42a2-ae67-eced37ca641e)

**Comment by merks** [comment]
@wimjongman 

I'm doing some testing now...

 The update site is structured like this:

![image](https://github.com/eclipse-birt/birt/assets/208716/6c0a17ea-3609-4539-9ae0-d5ddc7672ba1)

Using Oomph I can easily test installing all feature, other than the runtime features.  I see failures like this:

![image](https://github.com/eclipse-birt/birt/assets/208716/09198173-3c5a-490e-acce-d1d2027cd8ab)

I think we want to be really sure that one can install all the features of BIRT into a 2023-12 product with only the release train repository and the BIRT repository available.  That is my goal...

**Comment by merks** [comment]
@wimjongman 

With these changes, all user features of BIRT install into a 2023-12 installation.

https://github.com/eclipse-birt/birt/pull/1503

I think we're on a very good track to release on schedule. We just need to wait for final content from the dependencies, but I don't expect anymore significant changes on that front.  Woo hoo!

**Comment by wimjongman** [comment]
Nice, Ed! Thanks. 

So we have a quasi-final build. I will post on the mailing list and ask people to test it.

**Comment by merks** [comment]
Please let me create a milestone build tomorrow morning. I’ll post the link here.

**Comment by wimjongman** [comment]
Cheers!

**Comment by merks** [comment]
I produced this milestone this morning:

https://download.eclipse.org/birt/updates/milestone/S202311210608

The build had what appears to have been a network glitch at the very end; go figure.  In any case, I've tested installing everything from this milestone repository with a fresh empty bundle pool and it is intact.  I created various types of BIRT projects, a BIRT report, and launched the web viewer preview.  No errors in the error log.  All seems to be in good working condition.

**Comment by wimjongman** [comment]
Release review completed successfully.

**Comment by merks** [comment]
@wimjongman 

Given we have a stable build that has been tested without anyone raising any issues, I think it would be less risk to promote that to a release.  Should we get agreement from others?  When you give me the green light, I will kick off a release build...

**Comment by wimjongman** [comment]
+1 from me. 

What say @speckyspooky @hvbtup and @claesrosell?

**Comment by hvbtup** [comment]
+ 0.5 from me. I dont have an opinion, because ATM I just don't have the time to test anything.

**Comment by speckyspooky** [comment]
+1 from my side.

**Comment by claesrosell** [comment]
+1 from me.

**Comment by speckyspooky** [comment]
@wimjongman
I would think we can go ahead with the final built of BIRT 4.14

**Comment by merks** [comment]
It's been published.

https://download.eclipse.org/birt/updates/release/4.14.0

![image](https://github.com/eclipse-birt/birt/assets/208716/93f477a1-8e57-462b-a3dd-7c187af17ed4)

@wimjongman 

I'm not sure the procedure you use for incrementing versions for 4.15...

**Comment by wimjongman** [comment]
Scan and replace.


Best regards,

Wim Jongman
________________________________

**Comment by speckyspooky** [comment]
### Thanks at all for your support to get the BIRT 4.14 released - @wimjongman, @merks, @claesrosell, @hvbtup


Next step on my side will be together with my supplier to add "BIRT Runtime OSGi" into the main product
and we will execute specialized testing of it. If it successfully finished, then the main product can be published this month (December) with the newest BIRT version.

And my team will switch after the final testing from the BIRT 4.8 to 4.14 in full.

_(In other cases I come back with the findings but I hope we are fine, so I cross my fingers.)_

**Comment by merks** [comment]
FYI, some time will need to be spent incrementing versions for 4.15.  Also the target platform will need attention ASAP after the SimRel release on Wednesday, and Orbit has new versions such as a new version of POI.  But I travel on Wednesday and am in all day meetings Thursday, so if there are issues that need my attention Wednesday through Friday, some patience is likely required.
