### ISSUE TITLE
Master does not build anymore

### ISSUE THREAD

**Issue by claesrosell** [eclipse-birt/birt#1492]
The master branch doesn't build.

There are a lot of these in the build log:
```
[ERROR] The package javax.xml.namespace is accessible from more than one module: <unnamed>, java.xml
[ERROR] /home/jenkins/agent/workspace/build_master/viewer/org.eclipse.birt.report.viewer/birt/WEB-INF/classes/org/eclipse/birt/report/soapengine/api/AvailableOperation.java:[704] 
[ERROR] 	elemField.setXmlName(new javax.xml.namespace.QName("http://schemas.eclipse.org/birt", "Export"));
[ERROR] 	                         ^^^^^^^^^^^^^^^^^^^
```
The changes between the last successful build and the first failed build do not seem to be directly related to this error.  But for some reason the viewer does now have the package javax.xml.namespace accessible from both the JRE and ,probably, an OSGI bundle with `Automatic-Module-Name: javax.xml` .

I will start a -X build on my fork, hopefully I have more information in the morning.

**Comment by merks** [comment]
Strange, the build worked for me locally.  I'll kick another build...

**Comment by merks** [comment]
I don't know why the target platform change fixed the problem, but it did.  😨
