### ISSUE TITLE
UI displays long numbers in 2 lines

### ISSUE THREAD

**Issue by mcgrady32303** [eclipse-birt/birt#1501]
This is an annoying issue personally with BIRT 4.5.0  - I don't know if this is already fixed in the source.

When generating reports，BIRT will display long numbers in two lines. Refer to the picture below:
![LongNumber](https://github.com/eclipse-birt/birt/assets/4618927/270c4ee7-3f69-4edc-bb37-9fc31336f033)

JasperReport can cumstomize Text Field's attribute(Stretch Type、Position Type...).

Hope BIRT can add the feature.

**Comment by hvbtup** [comment]
You can customize the style in BIRT as well - using either highlight rules or `onCreate` events and `this.getStyle().xxx = "..."`.
But for me this doesn't make sense; usually you want the numbers to be aligned; which doesn't work if you use different fonts settings for each line; except if you determine the longest text (largest number) in the column before and use that to determine a style for each cell in the column.

**Comment by speckyspooky** [comment]
Have you a special way to produce the numbers. I tested a small example with fixed  numbers on a data element
and created a small test with 2 grids and 5 different long numbers formatted with the standard designer number.

But I cannot reproduce your case - see my screen.
Do you use "text" or "dynamic text" to produce your grid/table?

![figures](https://github.com/eclipse-birt/birt/assets/41593722/2ca8d1c1-23d4-44ac-8d25-e3bfa2059a5a)

**Comment by mcgrady32303** [comment]
> Have you a special way to produce the numbers. I tested a small example with fixed numbers on a data element and created a small test with 2 grids and 5 different long numbers formatted with the standard designer number.
> 
> But I cannot reproduce your case - see my screen. Do you use "text" or "dynamic text" to produce your grid/table?
> 
> ![figures](https://user-images.githubusercontent.com/41593722/284378613-2ca8d1c1-23d4-44ac-8d25-e3bfa2059a5a.png)


thx for your reply.

sorry,I made a mistake.

The problem is that a long number will not be displayed completely. Just like below:

The value is 123456789000, but the report generated displays 123456789.

Because each column of the table has a fixed width, then if the number is longer than the width, the excess part of the number will be obscured.

If long number could display in multiple lines with fixed width columns, the problem is solved.

Maybe I donot use birt in the right way, thx for your guidance.

**Comment by mcgrady32303** [comment]
Follow with the previous comment.

Long numbers could display in multiple lines, but I should specify the number of character where I put a 'Enter'.

The code is : fun.putEnter(dataSetRow['Value'], 9) .

If I get lots of reports, and each report gets lots of columns(fixed width), then I have to write the 'putEnter' code for every column.

If Birt could display long numbers in multiple lines automaticly, I will save a lot of repeated/trivial codes. And if I modify some columns of a table, perhaps, I got to calculate and rewrite the code.

**Comment by wimjongman** [comment]
Strings wrap for some reason but numbers don't wrap.

![afbeelding](https://github.com/eclipse-birt/birt/assets/180969/8a2242d2-eecd-4eea-aa1a-51ea5208f6f7)

**Comment by hvbtup** [comment]
An important information is missing until now: How exactly do you create your report and in which format?

**Comment by wimjongman** [comment]
Stalled. Please reopen if you have more information.
