### ISSUE TITLE
getDimensionValue(String) no longer available in nLayout

### ISSUE THREAD

**Issue by hvbtup** [eclipse-birt/birt#1502]
![grafik](https://github.com/eclipse-birt/birt/assets/7644776/d490287a-5b22-44d4-bc96-3247bd02eb3c)

![grafik](https://github.com/eclipse-birt/birt/assets/7644776/79b94467-e0fa-4382-a2ae-e00ccae288fe)

This code used to compile (and work); it is from my fork, not from this repo.

After merging the changes to master from the last 2-3 months, it does no longer work.

I am unable to find out why...

More important: How can I fix this?

I can't find a simple way to parse a CSS length value including unit and return a value that is in the same internal units as `getAbsoluteBP();`

**Comment by claesrosell** [comment]
We switched from Flute to Batik a while ago, but after a fast look at the code I couldn't see a getDimensionValue(String) prior to that switch either. You will need to create the correct CSSValue type from the fixYPosition string.

**Comment by hvbtup** [comment]
What I did finally was to create a new static method `parseAndConvertToInternalUnits` in `StringUtil`:

	/**
	 * This is a helper for vertical tab sizes in UserPorperties only.
	 *
	 * It does not support all the CSS units.
	 *
	 * @param userPropertyValue
	 * @return the value converted to internal units (one unit = 1/72000 inch).
	 */
	public static int parseAndConvertToInternalUnits(String userPropertyValue) {
		try {
			DimensionValue value = parse(userPropertyValue);
			if (value != null) {
				float v = (float) value.getMeasure();
				String unit = value.getUnits();
				if ("pt".equals(unit)) {
					return (int) (v * 1000);
				}
				if ("mm".equals(unit)) {
					return (int) (v * 7200 / 2.54);
				}
				if ("cm".equals(unit)) {
					return (int) (v * 72000 / 2.54);
				}
				if ("in".equals(unit)) {
					return (int) (v * 72000);
				}
				if ("pc".equals(unit)) {
					return (int) (v * 12 * 1000);
				}
			}
		} catch (PropertyValueException pve) {
			// For the time being, just ignore invalid values.
		}
		return 0;
	}

I then use it like this:

			String verticalTab = (String)cArea.getContent().getUserProperties().get("VerticalTab");
			int grenze = StringUtil.parseAndConvertToInternalUnits(verticalTab);
			int absBP = getAbsoluteBP();
			if (absBP > grenze) {
				...
