### ISSUE TITLE
Damaged build for macos

### ISSUE THREAD

**Issue by idefixcert** [eclipse-birt/birt#1514]
Hi All,
I just downloaded `birt-report-designer-all-in-one-4.14.0-202312020807-macosx.cocoa.x86_64.tar.gz`
and after opening the tar and executing the `eclipse.app` I see the following error.
`“eclipse.app” is damaged and can’t be opened. You should move it to the Bin.`
I saw the same error also with 4.13.0.

I have the following MacBook:
2,6 GHz 6-Core Intel Core i7
14.1.2 (23B92)

Can you please help on that?

**Comment by merks** [comment]
Such images are not notarized so mac might complain.  Likely you have to do some additional things:

https://appleinsider.com/inside/macos/tips/how-to-launch-any-macos-app-even-those-not-notarized-by-apple

**Comment by idefixcert** [comment]
I was able to fix it by:
`xattr -d com.apple.quarantine eclipse.app`

**Comment by merks** [comment]
Yes, that's the kind of thing I expect from an app that isn't notarized.  It's been a while since I used by mac virtual box.  Of course it would be better if we produced a notarized *.dmg, but that's really a time-consuming operation and I can only invest so much time in releng support...

**Comment by idefixcert** [comment]
I am fine with that, should we close the issue?

Thanx Ed

**Comment by merks** [comment]
Yes, we can close it.  I'm glad you found the correct way to get it to work and for sharing the details.
