### ISSUE TITLE
NPE in SvgFile.isSvg(String)

### ISSUE THREAD

**Issue by ilnur-z** [eclipse-birt/birt#1525]
Where is a NullPointerException on method org.eclipse.birt.report.engine.util.SvgFile.isSvg(String) then uri is null.
I think that because some brackets needed:

`
if (uri != null && ( uri.endsWith(".svg") || uri.toLowerCase().contains(URL_IMAGE_TYPE_SVG) ) ) 
`

(just like on method org.eclipse.birt.report.engine.util.SvgFile.isSvg(String, String, String))

caused by https://github.com/eclipse-birt/birt/commit/59c1d03895244d437e1153fd1ecd0e6e3ffb4b47

**Comment by wimjongman** [comment]
Please add the stacktrace

**Comment by ilnur-z** [comment]
here stacktrace

**Comment by ilnur-z** [comment]
ImageManager2 is our little modified ImageManager, which not takes rasterised data for svg-images

**Comment by speckyspooky** [comment]
Yes, I can confirm the NPE is based through the missing brackets.
I added a PR #1526 some minutes ago to fix it.
