### ISSUE TITLE
How do I test PCL plugin for the artifacts from PR 1531?

### ISSUE THREAD

**Issue by daverch** [eclipse-birt/birt#1540]
Hi there, 

I’m working on improving parts of BIRT’s more or less internal code, see
https://github.com/eclipse-birt/birt/pull/1531 

(This is meant for preparing JS script support for ExtendItems like RotatedText as a next step, but that’s a different topic).
What I did in PR 1531 was to add types to dozens of collections arguments and variables, e.g. List<WhatEver> instead of just List.

I guess the only place this could have a negative impact is when using plugins. 

So I’m asking:

Does anybody on the list develop or use custom plugins (except RotatedText) or know someone who does? 

It would be nice if anyone could test if the code changes from PR 1531 cause any problems for such plugins.

I don’t think this will be a problem, but it would be good to be sure before merging.

Mit freundlichen Grüßen
Henning von Bargen

**My PCL files are attached.**
[com.u2logic.xlr8.reporter.emitter.pcl.feature.zip](https://github.com/eclipse-birt/birt/files/13895590/com.u2logic.xlr8.reporter.emitter.pcl.feature.zip)

**Comment by daverch** [comment]
[com.u2logic.xlr8.reporter.emitter.pcl_4.24.5.zip](https://github.com/eclipse-birt/birt/files/13906121/com.u2logic.xlr8.reporter.emitter.pcl_4.24.5.zip)
Try this file.

**Comment by hvbtup** [comment]
@daverch I'm not going to test your code. Anyway, my changes are commited, so you can run your code with BIRT 4.16.
I'll close this issue. If you run into trouble with your code with BIRT 4.16 and you investigated it and come to the conclusion that it's related with changes in BIRT, feel free to open a new issue.
