### ISSUE TITLE
birt runtime 4.14 in docker container behind reverse proxy, fails to load with "mixed content" error due to requesting http://

### ISSUE THREAD

**Issue by brush** [eclipse-birt/birt#1559]
this is tomcat running inside a docker image, with birt being installed according to the instructions (download [birt-runtime](https://www.eclipse.org/downloads/download.php?file=/birt/updates/release/4.14.0/downloads/birt-runtime-4.14.0-202312020807.zip), unzip, copy WebViewerExample to webapps/, rename it).

tomcat is verified working correctly, runs its examples. the birt splash page works, see image. however, attempting to run the example reports (or any other) simply fails. see second image. if you use "/run?..." instead of "/frameset?..." you just get a blank screen. no logs in the birt log location, no apparent errors in the tomcat logs.

any ideas how to troubleshoot? thanks!

results in first splash page: https://[example.com]/birt-viewer/

![birt](https://github.com/eclipse-birt/birt/assets/63537/2e165541-3934-4332-adae-ae86d928b718)

results when clicking on sample report (ie. it's just showing the heading of the example): https://[example.com]/birt-viewer/frameset?__report=example_simple.rptdesign&paramString=my+parameter&paramInteger=2&paramList=2

![birt2](https://github.com/eclipse-birt/birt/assets/63537/420fc2ba-2b31-4e20-a768-b24f79c97f5a)

result when using same url with /run?..., ie. https://[example.com]/birt-viewer/run?__report=example_simple.rptdesign&paramString=my+parameter&paramInteger=2&paramList=2
: 

[blank]

**Comment by brush** [comment]
a note that i am receiving the following warning on startup, though not when attempting to run reports, which i have so far ignored since based on google searches it seems to not be relevant. but just in case:

`WARNING [http-nio-8080-exec-60] org.apache.axis.utils.JavaUtils.isAttachmentSupported Unable to find required classes (javax.activation.DataHandler and javax.mail.internet.MimeMultipart). Attachment support is disabled.`

**Comment by speckyspooky** [comment]
I tested it with "Apache Tomcat/9.0.76" and with Windows 11 and JRE 17.0.5.
Currently I'm not able to reproduce the noted issue:

### Tomcat, system infos
![2024-02-01 20_21_50-](https://github.com/eclipse-birt/birt/assets/41593722/19e47fe0-1d40-464a-a674-77bbc0b8a98c)

### Install-report
![demo-install](https://github.com/eclipse-birt/birt/assets/41593722/a0f84938-d84d-47b8-8bbd-a894c5426b7f)

### Chart-report
![demo-chart](https://github.com/eclipse-birt/birt/assets/41593722/3f5834d2-85ca-413b-b106-516557abe0ab)

**Comment by brush** [comment]
> I read your description could you post the 2 used URLs which you have used please. If I understand it correctly then you have only changed the URL-parameter "frameset" to "run". "frameset" shows the viewer correctly but with "run" you got the crazy page with the large icons.

no, sorry for the misunderstanding!

results in first splash page: https://[example.com]/birt-viewer/

results in second image (ie. it's just showing the heading of the example): https://[example.com]/birt-viewer/frameset?__report=example_simple.rptdesign&paramString=my+parameter&paramInteger=2&paramList=2

results in blank page: https://[example.com]/birt-viewer/run?__report=example_simple.rptdesign&paramString=my+parameter&paramInteger=2&paramList=2

**Comment by brush** [comment]
> I tested it with "Apache Tomcat/9.0.76" and with Windows 11 and JRE 17.0.5. Currently I'm not able to reproduce the noted issue:

thanks so much for checking! what would be a good next step? should i try downgrading my JRE and tomcat to the versions you used? or is there a way to more directly check where and why the report engine is failing??

**Comment by speckyspooky** [comment]
Do you use the "runtime" or the "osgi-runtime" of BIRT 4.14?
Currently I run into trouble with the osgi-runtime-version, the runtime-version works according to my screens.

**Comment by speckyspooky** [comment]
@merks 
Hello Ed, question to your side. I tested for this issue our "BIRT 4.14 osgi-runtime" and my Tomcat 9.0.76 noted a critical issue on starting phase of the BIRT webapp. But the message is very cryptical without helpfull details.
Have you an idea what the reason is or how I can get more details - screen & log added below.

I tested the "standard-runtime" and all is fine.


![tomcat-error-4 14 202312-osgi](https://github.com/eclipse-birt/birt/assets/41593722/44137b47-e0e6-4dde-847e-90f3b3f0e3df)

[tomcat-9.0.76-stderr.2024-02-01.zip](https://github.com/eclipse-birt/birt/files/14130517/tomcat-9.0.76-stderr.2024-02-01.zip)

**Comment by brush** [comment]
> Do you use the "runtime" or the "osgi-runtime" of BIRT 4.14? Currently I run into trouble with the osgi-runtime-version, the runtime-version works according to my screens.

i use the regular runtime. thanks for checking the others!

**Comment by brush** [comment]
> @merks Hello Ed, question to your side. I tested for this issue our "BIRT 4.14 osgi-runtime" and my Tomcat 9.0.76 noted a critical issue on starting phase of the BIRT webapp. But the message is very cryptical without helpfull details. Have you an idea what the reason is or how I can get more details - screen & log added below.
> 
> I tested the "standard-runtime" and all is fine.
> 
> ![tomcat-error-4 14 202312-osgi](https://private-user-images.githubusercontent.com/41593722/301637100-44137b47-e0e6-4dde-847e-90f3b3f0e3df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4MjEwOTAsIm5iZiI6MTcwNjgyMDc5MCwicGF0aCI6Ii80MTU5MzcyMi8zMDE2MzcxMDAtNDQxMzdiNDctZTBlNi00ZGRlLTg0N2UtOTBmM2IzZjBlM2RmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDIwNTMxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhZDQ4ZTkwYjc5OWU1OTIyZDFkYTBhZTg5NDBiOGYzODY4NDlmMTVhODFiMjgzNjljYmYwMjI1YjQzNTY0YzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hje6uIddWF4jfDUCXY_rzV257y7i5AlmNOkAxAtunbw)
> 
> [tomcat-9.0.76-stderr.2024-02-01.zip](https://github.com/eclipse-birt/birt/files/14130517/tomcat-9.0.76-stderr.2024-02-01.zip)

the warnings regarding TLDs i also get, but have assumed they are not a concern, per this: https://stackoverflow.com/questions/40204124/how-to-fix-jars-that-were-scanned-but-no-tlds-were-found-in-them-in-tomcat-9

however, the issue immediately after, regarding "one or more listeners failed to start" -- i have not got that error, nor anything else like it. that's my main problem -- the viewer appears to start normally, but then when running a sample report it fails silently. 

how do i increase loglevel in birt specifically?

**Comment by speckyspooky** [comment]
@merks & @brush 

I have a special logging configured of BIRT-WEB-INF-folder. The result is that I get a new log-file was written where an fault is documented.

`01-Feb-2024 21:54:19.864 SCHWERWIEGEND [main] org.apache.catalina.core.StandardContext.listenerStart Fehler beim Senden der 'Context Initialized' Benachrichtigung an den Listener aus der Klasse [org.eclipse.birt.report.listener.ViewerServletContextListener]
	java.lang.NoClassDefFoundError: org/apache/axis/AxisFault
		at org.eclipse.birt.report.service.ReportEngineService.<init>(ReportEngineService.java:203)
		at org.eclipse.birt.report.service.ReportEngineService.initEngineInstance(ReportEngineService.java:254)
		at org.eclipse.birt.report.service.BirtViewerReportService.<init>(BirtViewerReportService.java:83)
		at org.eclipse.birt.report.listener.ViewerServletContextListener.contextInitialized(ViewerServletContextListener.java:60)
`

Full file: 
[localhost.2024-02-01.zip](https://github.com/eclipse-birt/birt/files/14130954/localhost.2024-02-01.zip)


@brush 
The configuration file which I used is added under "...\Tomcat 9.0_Tomcat-9.0.76\webapps\birt\WEB-INF".
The file which I used is this configuration file which must be located directly into the WEB-INF-folder:
[logging.zip](https://github.com/eclipse-birt/birt/files/14130968/logging.zip)

**Comment by brush** [comment]
> @merks & @brush
> 
> I have a special logging configured of BIRT-WEB-INF-folder. The result is that I get a new log-file was written where an fault is documented.

thanks for the suggestion. i'm not sure it's working for me -- the entire time, i've been getting INFO-level logs. eg, i get the following when stopping and restarting the birt-viewer application from tomcat manager:

`
01-Feb-2024 22:01:17.087 SEVERE [http-nio-8080-exec-62] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks The web application [birt-viewer] created a ThreadLocal with key of type [java.lang.ThreadLocal] (value [java.lang.ThreadLocal@372138ae]) and a value of type [com.ibm.icu.util.ULocale] (value [en_US]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
01-Feb-2024 22:01:28.372 INFO [http-nio-8080-exec-64] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
01-Feb-2024 22:01:35.718 WARNING [http-nio-8080-exec-78] org.apache.axis.utils.JavaUtils.isAttachmentSupported Unable to find required classes (javax.activation.DataHandler and javax.mail.internet.MimeMultipart). Attachment support is disabled.
`
except that there are numerous of the SEVERE threadlocal errors, but only on "stop" from the tomcat manager.

might this be related?

**Comment by brush** [comment]
> @brush The configuration file which I used is added under "...\Tomcat 9.0_Tomcat-9.0.76\webapps\birt\WEB-INF". The file which I used is this configuration file which must be located directly into the WEB-INF-folder: [logging.zip](https://github.com/eclipse-birt/birt/files/14130968/logging.zip)

i attempted to do the analogous thing in my linux install, except changing "INFO" to "FINE". however, i am nbt seeing any change to logging behavior. the logs in /usr/local/tomcat/webapps/birt-viewer/logs are still empty, and the logs in /usr/local/tomcat/logs/catalina.2024-02-01.log still only go to level INFO. do i need to do more than stop and start the application? (because i'm in a docker container, stopping the tomcat process will flush all my test configs.)

**Comment by merks** [comment]
Sorry, I don't really know how all the class loader magic works for such things.  The axis library is in the dependencies:

![image](https://github.com/eclipse-birt/birt/assets/208716/72dbbf9b-98f9-4779-9b93-93dd167f2f53)

**Comment by speckyspooky** [comment]
Thanks Ed, I know that the apache.axis is included I same the library.

I htought you have an idea why OSGi goes in such trouble again. Buy the way I used WildFly 30.0.1 with the OSGI-version and Java 17 without the issue. So it is realy starnge and the Linux-behavior is strange too.

I will try our nightly built if it is running. If not I would open a separate issue.
I assume that my issue has nothing to do with the Linux-topic.

**Comment by speckyspooky** [comment]
The issue with the OSGi-version is solved. Was your downgrad successful?

**Comment by brush** [comment]
> The issue with the OSGi-version is solved. Was your downgrad successful?
> 
> If you have the issue again then could you please take a look into the web-console of the browser. Because there will be documented when erros will occurs based on JavaScript execution and other problems. May be we wil there there some specific error message which can help us to locate the issue a little bit more.

it appears the error is that BIRT is making many insecure requests. dozens of examples like the following: 

`
Mixed Content: The page at 'https://reports.example.com/birt/frameset?__report=example_simple.rptdesign&paramString=my+parameter&paramInteger=2&paramList=2' was loaded over HTTPS, but requested an insecure script 'http://reports.example.com/birt/webcontent/birt/ajax/utility/Debug.js'. This request has been blocked; the content must be served over HTTPS.
frameset:1 Mixed Content: The page at 'https://reports.example.com/birt/frameset?__report=example_simple.rptdesign&paramString=my+parameter&paramInteger=2&paramList=2' was loaded over HTTPS, but requested an insecure script 'http://reports.example.com/birt/webcontent/birt/ajax/lib/prototype.js'. This request has been blocked; the content must be served over HTTPS.
frameset:1 Mixed Content: The page at 'https://reports.example.com/birt/frameset?__report=example_simple.rptdesign&paramString=my+parameter&paramInteger=2&paramList=2' was loaded over HTTPS, but requested an insecure script 'http://reports.example.com/birt/webcontent/birt/ajax/lib/head.js'. This request has been blocked; the content must be served over HTTPS.
`

i can force it to work by changing the local browser to ignore such errors, but this is not a longterm solution. currently looking for ways to force a serverside patch, but ideally birt would make secure requests instead! ideas?

**Comment by merks** [comment]
It's not entirely clear to me where that http comes from

![image](https://github.com/eclipse-birt/birt/assets/208716/d49a059b-0037-4ea1-88c8-0602d07d3281)

Maybe you can help track down the source and what needs to change?

https://github.com/eclipse-birt/birt?tab=readme-ov-file#create-a-birt-development-environment

**Comment by speckyspooky** [comment]
@brush 
Especially for you have have changed my setup of my locat Tomcat 9.0.76 with an HTTPS-certificate (baes on openSSL).
The result is that I have a local-HTTPS connection and BIRT runs under HTTPS and also the JS-Files wil be loaded with HTTPS-connection.

Therefore I cannot confirm that this is a default error on BIRT side.
The question is why shoudl BIRT start with thinking on your Tomcat - special configuration?

He you get the screens of my execution, Tomcat-log and Tomcat-config for HTTPS.

### BIRT execution

![2024-02-16 21_10_57-](https://github.com/eclipse-birt/birt/assets/41593722/9a316160-2f6f-49f2-a547-91fae78ca79e)


### Log description of Tomcat

![log-openssl](https://github.com/eclipse-birt/birt/assets/41593722/d1fb484e-d402-443b-9972-597e411c96d5)

### Tomcat configuration

![config-tomcat](https://github.com/eclipse-birt/birt/assets/41593722/8013144f-b210-481f-a1a6-4aa130eb0220)

**Comment by brush** [comment]
yes, i realized last night that the issue is probably the result of being behind a reverse proxy. as i mentioned, i'm running tomcat in a docker container; this is then served by a traefik reverse proxy to manage ssl.

so birt is receiving http traffic from the reverse proxy, and assumes it should generate http requests.

existing behind a reverse proxy is a common use-case, so there should be some standard way to manage this. ideally there would be a configuration switch in birt that could force it to generate all-https requests. alternatively, as an interim measure, i'm working on a filter for tomcat that either asks the browser to upgrade all requests to https or does it on the fly. other thoughts?

**Comment by speckyspooky** [comment]
The change to work completely based on the HTTPS-protocol isn't so easy to implements such way in BIRT.
Because the whole infrastructure of BIRT includes also the eclipse integration and the preview mde of reports which is by default localhost.
Therefore such a kind of change isn't so easy like it sounds.
Yes, we could try it to do only for the web-server side via configuration. But it sounds strange for me "to change a software" to fix a topic on a proxy-server.
I didn't understand why the proxy change the reached requests from HTTPS to HTTP because then you have a security risk on your proxy-server.

**Comment by brush** [comment]
there likely is a way to configure this in tomcat. i'll update when i have something nailed down.

**Comment by brush** [comment]
to be clear -- it's common for reverse proxies that handle ssl/tls to terminate the session and then communicate with backend server in the clear, when the structure is such that this communication is secure (on the same server, or within a secured network). this is so backend servers don't have to provision ssl/tls, which can be can of worms. so i don't think that's a security risk. the problem is that the backend server needs to know to make https: requests in client-side scripts, even though it's getting http: incoming.

**Comment by brush** [comment]
yes, as usual there's a variety of ways to do it but probably the simplest is to add:

`
scheme="https" secure="true"
`

to the relevant connector in the tomcat root server.xml, in my case `/usr/local/tomcat/conf/server.xml`

now that section for me looks like:

```
    <!-- A "Connector" represents an endpoint by which requests are received
         and responses are returned. Documentation at :
         Java HTTP Connector: /docs/config/http.html
         Java AJP  Connector: /docs/config/ajp.html
         APR (HTTP/AJP) Connector: /docs/apr.html
         Define a non-SSL/TLS HTTP/1.1 Connector on port 8080
    -->
    <Connector port="8080" protocol="HTTP/1.1"
               scheme="https" secure="true"
               connectionTimeout="20000"
               redirectPort="8443"
               maxParameterCount="1000"
               />
```

**Comment by brush** [comment]
and i think that closes this issue? thanks so much everyone for working with me on this! hopefully it helps someone else...

**Comment by speckyspooky** [comment]
Yes, I set the scheme-property too (like my screen). Sounds good that we was able to support you :o)

**Comment by brush** [comment]
yes -- except the nuance in a reverse proxy situation is to put the scheme-property on a **non-SSL** connector, so it tells the webapp to generate https requests even though it's receiving http ones. and yes -- really appreciate the help thinking it through! especially the suggestion to look for client-side script errors in the debug console, i was for some reason assuming that any errors would be on server side.
