### ISSUE TITLE
Birt is disclosing the webserver and framework details

### ISSUE THREAD

**Issue by Sachinjuneja9090** [eclipse-birt/birt#1564]
<img width="313" alt="ss" src="https://github.com/eclipse-birt/birt/assets/160120608/85d44317-d749-46a7-b173-336cf080be3d">

**Comment by speckyspooky** [comment]
What is the specific detail? At your screen I can only see that the default Java-StackTrace will be created on your error-message.
If you mean that "springframework" and "jetty" can be read then it isn't a BIRT topic this is due to the usage of the standard StackTrace.

**Comment by speckyspooky** [comment]
I will close the issue because the stack trace is the standard behavior of BIRT-excepiotn.
If you send additional information we can reopen the issue.
