### ISSUE TITLE
Check for EMCAScript, Rhino engine: 1.17.10 "target platform" vs. 1.17.14 "Orbit" available

### ISSUE THREAD

**Issue by speckyspooky** [eclipse-birt/birt#1566]
I started a small research of the posibilities to activate EMCAScript 6
and during my analysis I fgured out that BIRT 4.14 use the Rhino engine with version 1.17.10 which is defined through the target platform.
But I thought that the project will fetch the Rhino version based on the Orbit project and Orbit use the Rhino version 1.17.14.

@merks 
Have you an idea how we can get the better version from Orbit or how can we switch the target platform version?
I'm a little bit confused that the target platform use the naming "javascript" and Orbit "Rhino", may be the "javascript" means a special version based on Rhino...(?)

![2024-02-18 18_23_01-Orbit Aggregation Summary Summary – Mozilla Firefox](https://github.com/eclipse-birt/birt/assets/41593722/874e28fc-3db1-4cb2-a95b-007effc13d64)

**Comment by merks** [comment]
Previously Orbit was rewrapping Maven artifacts that were directly available as OSGi bundles at Maven Central, but when I reworked Orbit, any Maven artifact directly available as an OSGi bundle is reused as is.  Sometimes this resulted in a change to the bundle symbolic name as is the case for this bundle.

Let's see how the build works out.  You'll see in the PR that lots of changes are in the various ant build files, and I'm never all the comfortable with what those scripts are doing...

**Comment by merks** [comment]
The changes are there now, so I think this issue can be closed.  But maybe you have some followup changes...

 FYI, WTP continues to have dependencies on the old bundle symbolic name, though they are aware that they should use the newer one:

![image](https://github.com/eclipse-birt/birt/assets/208716/246417e1-9b85-4420-905f-3f7e271dd3ea)

**Comment by speckyspooky** [comment]
Many thanks for the PR and the hints.
