### ISSUE TITLE
BIRT reports getting wrong date from date parameters

### ISSUE THREAD

**Issue by cwhauser** [eclipse-birt/birt#1575]
Reports not filtering accurately using date parameter(s).  If I change the date 1 day forward or backward it ends up filtering for the desired date.  This is now happening across numerous reports - at least a dozen or more reports.

**Comment by speckyspooky** [comment]
Coud you give use a report as template with the explanation on it to see what is the definition and what you expect to see.
Based on your description I cannot figure out it is a plan date parameter, where will be executed the date changes in which way and where will be used in which way the parameter.

The best way would be if you could provide a small test report with your topic (without external data sources).

**Comment by speckyspooky** [comment]
I will close the ticket. If you can send us more information for a research we can reopen the issue.
