### ISSUE TITLE
Should the github action archive so much stuff?

### ISSUE THREAD

**Issue by merks** [eclipse-birt/birt#1614]
@wimjongman 

I noticed that the ci github runner build takes longer than the ci jenkins build, and almost 1/2 the time is spent archiving things:

![image](https://github.com/eclipse-birt/birt/assets/208716/af37c915-bf99-4dc8-87a3-c34d9d1a12b4)

There are several Gs of data here.

![image](https://github.com/eclipse-birt/birt/assets/208716/9042dfd1-2a31-4fa9-b9d1-27c79fa11ee4)

Is that actually useful for anyone?

**Comment by merks** [comment]
And what I don't see, which is probably the most useful thing, are the test results...

**Comment by wimjongman** [comment]
Yes, this is not needed because we have our own build.

**Comment by merks** [comment]
Now the action finishes faster than Jenkins. About 18 minutes versus about 25 minutes. It’s good to get quick results. 

Do you know how to publish the test results?

**Comment by speckyspooky** [comment]
@merks
Your PR seems to be stuck in Jenkins. Your PR was the status of pending with the orange circle.
Ist there something going on?

I ask because a small change with a new PR stuck too due to Jenkins issue.

**Comment by speckyspooky** [comment]
ok, the first try this morning crashed, but the second try runs currently (crossed fingers)

**Comment by speckyspooky** [comment]
The new process works fine also the Tenkins is now running again.

**Comment by wimjongman** [comment]
Are the test results now published?

**Comment by merks** [comment]
No because I don’t know how. The never were published I think.

**Comment by wimjongman** [comment]
It seems to be possible: https://github.com/marketplace/actions/publish-test-results

**Comment by wimjongman** [comment]
if we require it.

**Comment by hvbtup** [comment]
Hmm,
actually I depend on the archiving of the Runtime and the All-In-One IDE.
From my experience, the CI build is much more reliable than building from inside the Eclipse IDE.
But, since I use a fork anyway, probably I can simply merge only parts of #1615 into my fork.

**Comment by hvbtup** [comment]
Another point - but I have to admit I have no idea here - If the artifacts are directly generated by the CI job on Github's servers, aren't they more trustworthy than artifacts that were build on someone's personal machine?
Or how are the artifacts actually generated, signed and transferred to our downloads page?

**Comment by merks** [comment]
The build results are produced by this job:

https://ci.eclipse.org/birt/job/build/

That job does builds PRs too, but it does not sign them and does not promote the results.
