### ISSUE TITLE
In the Linux environment, the Arabic language is not displayed in the template.

### ISSUE THREAD

**Issue by 935970041** [eclipse-birt/birt#1640]
Hello. The local test is normal. After the content is released to the remote end, the Arabic language is not displayed. Is it because the Arabic language is missing in the environment? How to confirm that the field is not displayed due to the lack of language? (English is OK)

**Comment by speckyspooky** [comment]
If you want to display Arabic language then it must be installed already on your server.
And you should check that your used font is configured at the font-configuration files of BIRT.

**Comment by 935970041** [comment]
Hi, there.  The Arial font library has been installed on the server. The font property of the rptdesign file is also set to Arial, but it is still not displayed. Do I need to set other properties?

**Comment by 935970041** [comment]
谢谢你，已经搞定了。 需要在 /usr/share/fonts/truetype下面 新增相关的ttf字体文件，然后再刷新字体

**Comment by 935970041** [comment]
Thank you, it's done.  Add related TTF font files to the /usr/share/fonts/truetype directory and update the fonts.
