### ISSUE TITLE
An "end" is missing to close the "begin" in Postscript emitter

### ISSUE THREAD

**Issue by ricetrac** [eclipse-birt/birt#1669]
We have been using BIRT in OSGI mode for several years in our project, and we noticed that the header.ps file present in the "emitter.postscript" library contained an error: an "end" was missing to correctly close a "begin".

https://github.com/eclipse-birt/birt/blob/dca18950145a0271bff47fa9522ac9e0203556a6/engine/org.eclipse.birt.report.engine.emitter.postscript/src/org/eclipse/birt/report/engine/emitter/postscript/header.ps#L140

We apply the correction directly to our project by unzipping the .jar file "org.eclipse.birt.report.engine.emitter.postscript", and modifying the "header.ps" file.

Is it possible to integrate the correction into the next version of BIRT?

Thanks.

**Comment by merks** [comment]
Pull requests are welcome. 🙏 

The setup is easy 

https://github.com/eclipse-birt/birt#create-a-birt-development-environment

**Comment by speckyspooky** [comment]
Could you please explain which PS-sequence is missing because I can see "}def" at line 140.
And I'm not a postscript developer so it would help if you can define the sequence which will be missed.

![postscript](https://github.com/eclipse-birt/birt/assets/41593722/2f031aaf-1595-4433-bf4f-b234388a5fd2)

**Comment by ricetrac** [comment]
Good morning,
I'm trying to make a Pull Request, but in the meantime, an "end" is missing just before the "}def" to close the "begin":

```
/drawstreamimage {
 gsave 5 dict begin
 /pix 2 index 3 mul string def
 /i 0 def
 6 -2 roll translate
 4 -2 roll 1 index 1 index 0 eq exch 0 eq or {
 pop pop 1 index 1 index}if scale
 8 2 index 2 index [ 3 -1 roll 0 0 0 6 -1 roll sub 0 0]
 currentfile /ASCIIHexDecode filter /FlateDecode filter false 3 colorimage
 end
}def
```

**Comment by speckyspooky** [comment]
@ricetrac 
Please check the raw file of PR #1673 I added the "end" element for ps-method "drawstreamimage" on header.ps.

**Comment by speckyspooky** [comment]
The change is merged to the master-branch.

**Comment by ricetrac** [comment]
@speckyspooky  

> @ricetrac Please check the raw file of PR #1673 I added the "end" element for ps-method "drawstreamimage" on header.ps. If it is ok from your side then I will commit the change to the BIRT-master.

it is OK for me. Sorry for the delay.
