### ISSUE TITLE
Sorting Column Bindings

### ISSUE THREAD

**Issue by LeonardoIPM** [eclipse-birt/birt#1699]
When selecting an Available Column Binding in an expression builder, for some reason, "Edit Bindings..." and "RowNum" are being sorting alphabetically also:

![Edit Bindings](https://github.com/eclipse-birt/birt/assets/167772501/2a261825-acf2-4ff2-9b69-7c39c7269fe1)

In older versions, these options were always in the bottom. Could you take a look at this?

**Comment by speckyspooky** [comment]
Your mentioned behavior/sorting was changed from BIRT 4.6 to BIRT 4.8. This change is more like 10years ago.
From my point of view this isn't a bug.

You are welcome to change the behavior.

**Comment by speckyspooky** [comment]
The change was done on Feb 8, 2017 with commit 4403ba0

The topic is according to the description that 3 new "ViewerComparator" was set to each of the expression builder views
also to the 3rd VIew `functionTable.setComparator( new ViewerComparator( ) );`
But with the 3rd comparator the original sorting order and the functionality of the sort-button was lost.

I will provide a PR to fix it.

**Comment by speckyspooky** [comment]
The fix is merged into the master branch.
