### ISSUE TITLE
How to initialize Date picker in report parameters in birt 

### ISSUE THREAD

**Issue by SuriyaCody** [eclipse-birt/birt#1705]
Hi everyone,

i am building a report in birt 4.15.0 and i don't have Date picker as an option. Please help me with this.

Thanks in advance

**Comment by merks** [comment]
Maybe someone will know the context of your question, but probably better you show a screen capture where you are looking for a data picker.  It's easy to just paste an in into the comment field.

**Comment by SuriyaCody** [comment]
![image](https://github.com/eclipse-birt/birt/assets/167118024/6b28096d-2556-42ba-bf58-e22522aa7917)
i want date picker in display type

**Comment by speckyspooky** [comment]
The DatePicker will be activated at the option "Format as" and there is a list entry for the DatePicker based on the medium date.

![grafik](https://github.com/eclipse-birt/birt/assets/41593722/cc5624c5-8142-451e-93cf-fabdd1dba682)

**Comment by SuriyaCody** [comment]
Thanks. Its working

**Comment by speckyspooky** [comment]
Sounds good!

**Comment by merks** [comment]
I picture is worth a 1000 words.  😀
