### ISSUE TITLE
Use edge as default browser and use modern help

### ISSUE THREAD

**Issue by wimjongman** [eclipse-birt/birt#1736]
I would like to activate the modern help and use edge as the default browser.

```
-Dorg.eclipse.swt.browser.DefaultType=edge
-Dorg.eclipse.help.webapp.experimental.ui=true

```
## L&F of the modern help
![image](https://github.com/eclipse-birt/birt/assets/180969/7063893b-cb75-4175-bd98-6d053448b5a4)

**Comment by merks** [comment]
I guess that edge setting is one that you should only set for Windows we have to be a bit careful how we do that in the product file...

**Comment by wimjongman** [comment]
I think it will not harm if edge is not available. It will go to the default.

**Comment by wimjongman** [comment]
But I made the change anyway.
