### ISSUE TITLE
Excel emitter configuration: enhance the designer "advanced property"-register to setup the configuration

### ISSUE THREAD

**Issue by speckyspooky** [eclipse-birt/birt#1770]
Currently the Excel-emitter (spudsoft) has lot of user-properties tp control the excel output.
The handling of the user properties is not simple because you have to know that the properties exists and it must be reserach in our BIRT-project source.

To support a bit mor of user friendly handling I will start to enhance the advanced register with the most common user-properties as configurable properties directly at design file level.

The internal handling will gve the user-properties a higher priority instead of the configuration.
This means is an user property configured then this value will be used and not the design file configuration to avoid issue with older versions.

The first change will only handle a few properties as starting point.
Afterwards with further PRs next options will be available.

And also the configuration of further emitter like "PDF" can be added here in future.

### Screen of the new configuration options

![display-excel-emitter-config](https://github.com/eclipse-birt/birt/assets/41593722/45cd7d6f-6cad-4ae7-abf7-e4c41ec0d7fb)

**Comment by hvbtup** [comment]
Nice idea!
