### ISSUE TITLE
Issue on Double-Byte-Characters: text-parameters do not display correctly on PDF/XLS/XLSX/DOCX (e.g. CN, GR, DE-Umlaut)

### ISSUE THREAD

**Issue by bossyang** [eclipse-birt/birt#1800]
BIRT WebViewer 4.16

When report parameter value contains Chinese character, the dataset does not return data. 

In the following example, let's say parameter value is "积极会员" . 
It will work in HTML format.
![BIRT-20240717-003](https://github.com/user-attachments/assets/03f7cb57-a27c-4a4c-8bf3-f3c510d8d020)

But fail in pdf/xls/docx format.

![BIRT-20240717-002](https://github.com/user-attachments/assets/f9c87c18-88c1-49b0-bcc0-cc145caee40e)

**Comment by speckyspooky** [comment]
I have tested your description with BIRT 4.16 standardinstellation MS Windows 11.
The result looks good on my side for HTML, PDF, DOCX & XLSX.

Attached you will find my test-report and the according results. Can you please execute my report to see the results on your BIRT-version.

Additional on it, can you provide an example from your side with the problem but without external dependencies and external data sources.

### Grafik of my pdf result
![grafik](https://github.com/user-attachments/assets/ae4773ac-5fa3-4350-ac39-451633187761)

### Test results
[language-chinese.zip](https://github.com/user-attachments/files/16273013/language-chinese.zip)

**Comment by speckyspooky** [comment]
Of course, you are right and there is really a problem with all double-byte-characters according your description,
with the run types **"run"**, **"preview"** the UTF-8-characters won't be handled correctly.

If the run type **"frame set"** is used, then all looks fine.

The problem exists in BIRT: 4.14, 4.15, 416
(Currently I'm not able to test older versions and the current build.)


![double-byte-cha
[languages_2byte.zip](https://github.com/user-attachments/files/16310370/languages_2byte.zip)
racters-finding-BIRT-4 14-4 15-4 16](https://github.com/user-attachments/assets/9a32ece7-d310-4795-bede-d1c60f9a6b5a)

### New version with different Double-Byte-Languages
[languages_2byte.zip](https://github.com/user-attachments/files/16310371/languages_2byte.zip)

**Comment by speckyspooky** [comment]
@wimjongman , @hvbtup , @merks 

Hi guys,
here we have a problem (I doesn't like such kind of problems) and I know that this has to do with the double-byte-characters and the UTF-8 handling.
Therefore I checked my demo eclipse BIRT 4.14 for the UTF-8 encoding at eclipse side and JVM (screen attached) but it looks fine.
Have you directly an idea whether it is a general configuration to solve that?
Currently I hadn't any success and wants to ask you before we have to start a deep dive.

In the history I had the same issue on my platform but there I configured the "-Dfile.encoding" to UTF-8 and all was fine afterwards. But in our case it doesn't work and have no good idea.

Strange is that the "frameset"-call is working correctly with the parameters so they will be correct encoded for the output.

![config-utf-8](https://github.com/user-attachments/assets/ad4cb3bb-dcf0-4120-8d52-73569d29295d)

**Comment by hvbtup** [comment]
No idea.
But if it worked correctly with BIRT 4.8 and with 4.14 it doesn't work correctly, with otherwise identical environments (web browser, OS, etc), then it is obviously related to changes between these versions.
Of course there are *lots* of changes in the source code, but maybe the reason isn't even in source.
I suspect:
Either there are changes in the sources regarding URL parsing (and/or writing)
Or a library that BIRT uses for this has changed behavior.

**Comment by speckyspooky** [comment]
Now I was able to test the demo report for all my windows versions and here are the result.

Result are fine for BIRT: 4.6, 4.8

Results with character error: since BIRT 4.9
(I tested 4.9, 4.10,  4.12,  4.13,  4.14,  4.15,  4.16,  4.17)

**Comment by speckyspooky** [comment]
I figured out that the issue was based on the viewer requests where the old encoding "ISO-8859-1" was used instead of "UTF-8".

The fix is available with PR #1805 

### Screen of the retest with the direct preview
![2024-07-19 21_32_48-](https://github.com/user-attachments/assets/956a901a-1a0b-400c-963b-e29dad0310f0)

**Comment by speckyspooky** [comment]
The fix is merged to the master branch and will be available with BIRT 4.17
