### ISSUE TITLE
Track down tests that fail to render their expected image content

### ISSUE THREAD

**Issue by merks** [eclipse-birt/birt#1828]
It's not clear which changes in the target platform contents cause new rendering problems.  I will mark the tests as ignored with a link to this issue for future investigation so that I can make progress with updating to a new version of derby.

**Comment by merks** [comment]
These tests pass in the IDE and only fail when run from Tycho surefire:

![image](https://github.com/user-attachments/assets/43ede4cf-c6ef-43ee-8e02-ba091d49c7be)

![image](https://github.com/user-attachments/assets/57168781-2f9d-4932-a65a-37b41d862c2d)

Tracking down the difference is challenging.

**Comment by merks** [comment]
These tests even pass when I set the target platform to be the generated *.target file.

**Comment by claesrosell** [comment]
I have checked out the latest stuff from master and re-enabled the disabled tests but cannot reproduce these failing tests in my Linux environment.
Is there a simple way to reproduce at least one failing test in the IDE?

**Comment by merks** [comment]
No, in the IDE they pass on Windows but not in the Maven build.  Maybe even on Linux they pass both in the IDE and in the Maven build.  So no, I don't know how to reproduce the failure in the IDE.  😢

**Comment by merks** [comment]
Did you try the Maven build locally?

![image](https://github.com/user-attachments/assets/e794e514-c501-4dbb-914e-666e7d3a3cd9)

**Comment by claesrosell** [comment]
I haven't tested a Maven build yet, but I will do it tomorrow. If I can reproduce a simple failure, like the draw rectangle test, perhaps I can remote debug it. I have never remote debugged a test run with surefire before, but it seems to be supported

**Comment by merks** [comment]
@claesrosell 

Thanks for trying to help.  It looks like the failure is only on Windows and only when launched from the Maven build so I won't invest further time in this and the verification builds will continue to test these as before.
