### ISSUE TITLE
BIRT, link styling "bookmarks" & "hyperlink": use configured styling and avoid standard hyperlink text decoration (#1025)

### ISSUE THREAD

**Issue by speckyspooky** [eclipse-birt/birt#1864]
BIRT support for label- and data-element the option to configure hyperlinks.
Hyperlinks can be web-links, bookmark-links or drill-through-report-links.

The current layout handling is to simulate the standard hyperlink text decoration like web-links.
So a label with auto-font-color "black" will be displayed with font-color "blue" and underline.
If another font-color like "auto" selected then this will be used but the underlined text remain.

The use case is on my side to implements "table of content" for statistic reports as summary for output PDF & DOCX.
In this cases I want to use myown configured layout style instead of the standard handling but currently it is not possible.

**The plan of this feature-request will be:**
1. Implementation of an option to **disable** the hyperlink text decoration as a standard layout option or keep it as it is.
2. Output types: HTML (preview), PDF, DOCX, XLS, XLSX, PPT shall be changed
3. The option can be set on script level
4. The link-click-event-handling won't be changed, only the styling will be optimized.

**Out of scope of the change:**
- The change will not implements the different text-decoration options which are available for web-pages.

I started a research and figured out that the handling of the hyperlink styling is different for all output formats.
Therefore the implementation will be done indivdually.

### Screen of the planned designer change - font style
![grafik](https://github.com/user-attachments/assets/ee4edc6b-7254-478a-ae3e-400a84a7276b)

### Example of the output "Preview" & "PDF"
![grafik](https://github.com/user-attachments/assets/0be048bf-5103-40f5-92c6-7619cc0b422e)

I will provide a first draft PR for that feature-change.

**Comment by hvbtup** [comment]
Maybe you could even add a style with a specific name (e.g. "hyperlink") that is applied to hyperlinks instead of the standard styling.

**Comment by speckyspooky** [comment]
I will change the new HTML-CSS-class to a more generic value like "hyperlink-undecorated".
The internal naming will be "textDecoration" because this change could be enhanced in a later version to all available style options.

**Comment by wimjongman** [comment]
What will happen to the current reports that people have?

**Comment by speckyspooky** [comment]
The missing entry will bei added Automatically,
so the reports will work like before.
The default is standard handling with hyperlink style.
