### ISSUE TITLE
How to get the total page count of autolayout birt report  and store it in persistent global variable to used it for future used?

### ISSUE THREAD

**Issue by Sanket-Kuldharan** [eclipse-birt/birt#1881]
How to get the total page count of autolayout birt report  and store it in persistent global variable to used it for future used?
I tried for the same using on render script but total page type autotext component shows value like page number.
**Important note:** Inbuilt variable 'totalPage' shows incorrect value for autolayout type birt report.community please give me ideas regarding this.

_Originally posted by @Sanket-Kuldharan in https://github.com/eclipse-birt/birt/discussions/1749_

**Comment by speckyspooky** [comment]
I have added all information to the original discussion #1749.
You will find the details at discussion #1799 (page numbers) & #1848 (persistant global variables).

I hope this will help you.

**Comment by parth-codes22** [comment]
@speckyspooky , Is there any way to get the total page count of fixed layout birt report?

I have mostly textual dynamic content which I want to flow accross pages using **pageBreakInside: avoid** property on text / grid. But when the content is shifted to the next page the **pageNumber** & **totalPage** variables are not correct. How can I set them to persistent global variable?

Please find the attached sample report design for reference.

[sample.zip](https://github.com/user-attachments/files/28896403/sample.zip)
