### ISSUE TITLE
SOAP response, delete hostname.

### ISSUE THREAD

**Issue by mrEugenS** [eclipse-birt/birt#1887]
In case of errors in soap responses, the internal server name appears in the detail/hostname section.
Adding for all AxisFault from the search fault.removeHostname (); solves the bulk of problems.
But something else is responsible for issuing SAXParseException. I see that the generation of such errors is possible in many files (~ 150), but I cannot find the piece of code responsible for the final formatting/issuance to the user in order to suppress the display of hostname there.
I ask for help with this issue.
![image](https://github.com/user-attachments/assets/55764696-f3f8-49bf-9ae1-4d7911acdddd)
![image](https://github.com/user-attachments/assets/7ead1e10-e8d2-45ed-bab6-fea15204971b)

**Comment by wimjongman** [comment]
This is not a BIRT issue. If so, please reopen and provide more information.

**Comment by mrEugenS** [comment]
Good afternoon.
Yes, as a person not related to java development, the most difficult thing was to understand that the generation of these specific errors is not in the source codes.
But this is solvable using the Intercepting filter pattern for org.eclipse.birt.report.filter.
Although perhaps there are easier solutions about which I have no idea.
