### ISSUE TITLE
Birt 4.15  and 4.16 All in One Designer Soap Dataset Xerces Error

### ISSUE THREAD

**Issue by Sebtasticxz** [eclipse-birt/birt#1889]
Hey,

i get this error when i try to edit a Soap Dataset.
It might be the following Problem from Xerces?
https://issues.apache.org/jira/browse/XERCESJ-1689

![image](https://github.com/user-attachments/assets/beb748da-1f64-49fa-b4ff-4d530581c16b)

Error:
An error has occurred. See error log for more details.
failed to access class org.apache.xerces.dom.NodeListCache from class org.apache.xerces.dom.CoreDocumentImpl (org.apache.xerces.dom.NodeListCache is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @ebaf901; org.apache.xerces.dom.CoreDocumentImpl is in unnamed module of loader java.net.URLClassLoader @721af8d0)

**Comment by Sebtasticxz** [comment]
Hi merks, sorry for the late response.

I migrated from Birt 4.4.2 runtime to 4.15 runtime.
4.15 uses xerces 2.12.2.

I seems to me the problem is only, for my current existing reports. 
Everything is fine in the old Designer IDE. Only in the new one does the problem occur

When ich create a new report , the problem doesnt occur.
I will let you know when i have found out more.

**Comment by speckyspooky** [comment]
Please let us know if you would need additional support here.
In the meantime I will close the issue.
