### ISSUE TITLE
Birt 4.15 white stripe at the right and bottom side when using svg image in the image report item

### ISSUE THREAD

**Issue by Sebtasticxz** [eclipse-birt/birt#1894]
After the Upgrade from Birt 4.4.2 runtime to 4.15 runtime i get this strange white stripe on the right and bottom side.
The problem occurs only for svg files.
I have tried all kinds of styling things
Is this a bug? 

I attach 2 Example reports one with svg and one with a jpg.
You probably have to reset the image path and width and heigth to 170mm of the image.

[svgImageProblem.zip](https://github.com/user-attachments/files/16887285/svgImageProblem.zip)

SVG:
![image](https://github.com/user-attachments/assets/9219a37b-3d47-4739-b493-cacc63f2db81)
JPG:
![image](https://github.com/user-attachments/assets/bac35aab-f7f5-4084-ab3a-52fee341d460)

**Comment by speckyspooky** [comment]
Could you please write at which output you see the svg-border because I don't know if its HTML, PDF, WORD, etc.
Have you created the output from the web-viewer preview or have you created the the output directly from the designer?

**Comment by Sebtasticxz** [comment]
None of the above.
We have a microservice where the birtruntime is integrated and the birt engine renders / produces the report and stores the file.
The error only occurs with Pdf.
Docx is displayed correctly.

**Comment by speckyspooky** [comment]
I have checked your PDF documents and if I open the created PDF-docments with Adobe Reader then I see in both cases the gray border and the border on the SVG is directly at the image.
If I open the PDF-documents with FireFox then I see the results from your screen.

Currently I think that it is a topic dependent on the PDF-viewer  and add the end create the PDF-emitter here the library "openPDF" the final PDF-document. So we haven't any option to investigate on this gray border.
I cannot say why it is created there.

**Comment by speckyspooky** [comment]
So I'm back part 2. I check some different image formats with the same gray border and then I saw the base topic which isn't an image format issue.

Your image on your reports has a gray border and if the border is removed then you won't see the mentioned gray frame.
Here your report settings:

![grafik](https://github.com/user-attachments/assets/6dde39ca-a980-479c-bbab-db343aa49e19)

**Comment by Sebtasticxz** [comment]
I want this gray Border, but not this white stripe. Which is not present in Birt 4.4.2
I have checked the File in Acrobat Reader and see the white stripe.
[svg_with_white_stripe.pdf](https://github.com/user-attachments/files/16903437/svg_with_white_stripe.pdf)

**Comment by speckyspooky** [comment]
May be you can add the background with the same gray and then you have it.

**Comment by Sebtasticxz** [comment]
The background does not work. I have set the background to silver everywhere from the grid to the image. Nevertheless, the white stripe remains. :(

**Comment by Sebtasticxz** [comment]
It works, but now I have a thicker edge on the right and at the bottom.

![image](https://github.com/user-attachments/assets/12b140f6-f6a0-49f5-b0f2-f3546f2d4099)

**Comment by speckyspooky** [comment]
The only thing what I could prefer to your side is to add the gray line directly to your image jpg/svg and avoid the border of te image.
The internal topic is that there are lot of calculations from the image size to the internal output dimensions and it could be that there will appear rounding differences and these could be avoid. This is a topic in generally and so I think you couldn't avoid it with border or backround setup but with border on your image directly you can solve it and it should be possible at your svg-template where you integrate the image.
