### ISSUE TITLE
org.eclipse.jdt.core.IClasspathEntry.getPath() is null

### ISSUE THREAD

**Issue by Mastergord** [eclipse-birt/birt#1952]
An unexpected internal exception occurred. Please see log for detail.
  Plug-in Provider:Eclipse BIRT Project
  Plug-in Name:BIRT Designer UI
  Plug-in ID:org.eclipse.birt.report.designer.ui
  Version:4.17.0.v202409011308
  Error Code:Error.GUIException.invokedByUnexpectedException
  Error Message:Cannot invoke "org.eclipse.jdt.core.IClasspathEntry.getPath()" because the return value of "org.eclipse.jdt.core.JavaCore.getResolvedClasspathEntry(org.eclipse.jdt.core.IClasspathEntry)" is null
  
 Any ideas how resolve this problem?

**Comment by merks** [comment]
Is there no full stack trace available in the Error log view for this?  I can't tell where this is coming from just from the error message...

Is this using the latest build?

https://download.eclipse.org/birt/updates/nightly/latest

**Comment by speckyspooky** [comment]
I close the ticket. Let us know if you need further support of this topic then we would need additional information.
