### ISSUE TITLE
BIRT 4.14.0 - Parameters (String/Date) without "Is Required" are not updated when the report is executed 

### ISSUE THREAD

**Issue by Sachinjuneja9090** [eclipse-birt/birt#1960]
In BIRT 4.14.0, there's an issue where String and Date parameters that are not marked as "Is Required" are not updated properly when the report is run. This means that if a parameter is left blank or has a default value, and it's not set as "Required," BIRT doesn't update or apply the new value when the report is executed.

This problem didn’t occur in BIRT 4.8, where these parameters worked correctly.

**Comment by speckyspooky** [comment]
I did not understand exactly the issue of your description can you provide some screens of the problem.
And the best case would be a small test example where we can follow your problem. 
Have you tested newer versions to like BIRT 4.16/BIRT4.16?
Is a specific output format involved or a problem in generally?

I have done a smaller test with optional parameters and optional parameters with default values but I see no update problem on runtime of a report.

My small test example:

![grafik](https://github.com/user-attachments/assets/82f15c49-a14f-4bab-9ab6-4755bed568f0)

[parameter_optional_BIRT_4.14.zip](https://github.com/user-attachments/files/17637386/parameter_optional_BIRT_4.14.zip)

**Comment by Sachinjuneja9090** [comment]
Thanks, @speckyspooky!

The issue was due to some customizations made by us in the TextBoxParameterFragment.jsp file. We have identified the cause, and it turns out it was not related to BIRT.

Thanks again for your help! 😊
