### ISSUE TITLE
Combo box and List box which allow multiple values - reportContext.getParameterDisplayText() return null

### ISSUE THREAD

**Issue by jarorehu** [eclipse-birt/birt#1967]
Hello all,
for parameters with multiple values - combo or list box - you can use this code to get selected values:

```
reportContext.getParameterValue("parm1").join(",")
or simple
params["parm1"].value.join(",")
```

But this doesn't work for displayed text for options (labels)

```
reportContext.getParameterDisplayText("parm1").join(",")
```
**TypeError: Cannot call method "join" of null**

Function getParameterDisplayText() return value only for combo without "allow returning single value". Is it bug or is there some simple option to get Text for multiple checked values?

Regards

**Comment by speckyspooky** [comment]
I started a small investigation and of course currently this option is unsupported.
It is not a bug, the source code contains a hint that the display text is unsupported of multi selection parameters.

**Comment by speckyspooky** [comment]
Currently I try to figure out the reason and will check if there is an improvement possible.

**Comment by speckyspooky** [comment]
The situation till BIRT 4.17 is like discribed that the feature is unsupported.
With ticket #1981 an enhancement is planned and can be provied in best case with BIRT 4.18.
