### ISSUE TITLE
can not deploy BiRT report viewer

### ISSUE THREAD

**Issue by washaqq** [eclipse-birt/birt#1971]
Hi,
i installed Tomcat versions 9, 10 and 11 to deploy BiRT Viewer version [4.17.0](https://www.eclipse.org/downloads/download.php?file=/birt/updates/release/4.17.0/downloads/birt-runtime-4.17.0-202409160710.zip) by following https://eclipse-birt.github.io/birt-website/docs/integrating/viewer-setup/ but it doesn't work as stated in the instructions, i want to start over so can you tell me which Tomcat and Java versions i should install to make BiRT Viewer 4.17.0 work, i use windows 10.

Below you can see which Tomcat and Java versions are installed, All Tomcat work on different ports.

![image](https://github.com/user-attachments/assets/b5f2d01d-48e5-49d0-bea3-85e3e8138d76)
![image](https://github.com/user-attachments/assets/8cc5c74a-7b78-4943-aa0d-79bc56709b0b)
![image](https://github.com/user-attachments/assets/6dda6b2f-7057-40b8-a606-cb9859a9e162)

![image](https://github.com/user-attachments/assets/e186cd16-c64c-43bf-8bd7-e3f123ac16d1)
birt doesnt start.

![image](https://github.com/user-attachments/assets/fb9f10e9-3539-4625-8a58-50a7174b7bef)
This is the Error i get on All Tomcat versions
Thanks.

**Comment by speckyspooky** [comment]
You can use only Tomcat 9.x BIRT will not run with Tomcat 10.x.
Check you Tomcat log which errors will be written there.

If you need further support please add the server-log and the exactly version of BIRT which you have used because these information are not listed for BIRT like standard runtime or OSGi-runtime.

**Comment by washaqq** [comment]
Hi @speckyspooky,
Thank you for reply, I gave the version I used in the first post as a link, here it is again; https://www.eclipse.org/downloads/download.php?file=/birt/updates/release/4.17.0/downloads/birt-runtime-4.17.0-202409160710.zip

there is no server-log in Tomcat 9 logs but i put all the logs under log/ folder;

[catalina.2024-11-12.log](https://github.com/user-attachments/files/17732285/catalina.2024-11-12.log)
[catalina.2024-11-13.log](https://github.com/user-attachments/files/17732286/catalina.2024-11-13.log)
[commons-daemon.2024-11-12.log](https://github.com/user-attachments/files/17732287/commons-daemon.2024-11-12.log)
[commons-daemon.2024-11-13.log](https://github.com/user-attachments/files/17732288/commons-daemon.2024-11-13.log)
[host-manager.2024-11-12.log](https://github.com/user-attachments/files/17732289/host-manager.2024-11-12.log)
[host-manager.2024-11-13.log](https://github.com/user-attachments/files/17732290/host-manager.2024-11-13.log)
[localhost.2024-11-12.log](https://github.com/user-attachments/files/17732291/localhost.2024-11-12.log)
[localhost.2024-11-13.log](https://github.com/user-attachments/files/17732292/localhost.2024-11-13.log)
[localhost_access_log.2024-11-12.txt](https://github.com/user-attachments/files/17732293/localhost_access_log.2024-11-12.txt)
[localhost_access_log.2024-11-13.txt](https://github.com/user-attachments/files/17732294/localhost_access_log.2024-11-13.txt)
[manager.2024-11-12.log](https://github.com/user-attachments/files/17732295/manager.2024-11-12.log)
[manager.2024-11-13.log](https://github.com/user-attachments/files/17732296/manager.2024-11-13.log)
[service-install.log](https://github.com/user-attachments/files/17732297/service-install.log)
[tomcat9-stderr.2024-11-12.log](https://github.com/user-attachments/files/17732298/tomcat9-stderr.2024-11-12.log)
[tomcat9-stderr.2024-11-13.log](https://github.com/user-attachments/files/17732299/tomcat9-stderr.2024-11-13.log)
[tomcat9-stdout.2024-11-12.log](https://github.com/user-attachments/files/17732300/tomcat9-stdout.2024-11-12.log)
[tomcat9-stdout.2024-11-13.log](https://github.com/user-attachments/files/17732301/tomcat9-stdout.2024-11-13.log)

Kinds.

**Comment by speckyspooky** [comment]
I have done a test with BIRT 4.17 runtime (none OSGi) according to your version with Tomcat 9.0.88.

Tomcat looks fine.
BIRT 4.17 looks fine and standard test reports will be created.

![grafik](https://github.com/user-attachments/assets/913cbcf3-ae6f-486c-ab63-2db1be87aa6f)

![grafik](https://github.com/user-attachments/assets/08559464-c468-4949-b424-01e371c9e2c1)

**Comment by washaqq** [comment]
> I have done a test with BIRT 4.17 runtime (none OSGi) according to your version with Tomcat 9.0.88.
> 
> Tomcat looks fine. BIRT 4.17 looks fine and standard test reports will be created.
> 
> ![grafik](https://private-user-images.githubusercontent.com/41593722/385775755-913cbcf3-ae6f-486c-ab63-2db1be87aa6f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1MDQ2MjIsIm5iZiI6MTczMTUwNDMyMiwicGF0aCI6Ii80MTU5MzcyMi8zODU3NzU3NTUtOTEzY2JjZjMtYWU2Zi00ODZjLWFiNjMtMmRiMWJlODdhYTZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEzVDEzMjUyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1MDQ2ZTVmNTUzZGVlZmNiNTAzZWRkNmY2OWU5YjJhMGMxYTQ5MzZkOGE3YTI0NTA3OGIxMWQ0MjE1NTRhYTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.z3Uj_xn67xWAOI6R-oJAx5D20-hzwz_jsQH-2KSwcV4)
> 
> ![grafik](https://private-user-images.githubusercontent.com/41593722/385775855-08559464-c468-4949-b424-01e371c9e2c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1MDQ2MjIsIm5iZiI6MTczMTUwNDMyMiwicGF0aCI6Ii80MTU5MzcyMi8zODU3NzU4NTUtMDg1NTk0NjQtYzQ2OC00OTQ5LWI0MjQtMDFlMzcxYzllMmMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEzVDEzMjUyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwZWJjMzBmNDk1ODk4NWI4YWZjZjFlNzc1MDA3OGVjZjJiNDkzMzAzMDg3NWRkMjZhMGIzNGNmNzBiZjMzZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.M1zU_ZdvyuKJzwF-GZdkG9LdKlYrD-6bAH_0qZVrxNU)

Thank you for reply,
it is like working on my computer :), I don't know what is wrong but it doesn't work in my computer, can you tell me step by step how you deployed it, if possible? what java version (link if possible) you used? 

Thanks.

**Comment by washaqq** [comment]
> I have done a test with BIRT 4.17 runtime (none OSGi) according to your version with Tomcat 9.0.88.
> 
> Tomcat looks fine. BIRT 4.17 looks fine and standard test reports will be created.
> 
> I didn't found directly a hint on your files. May be you can redo your testing. I used your BIRT-version, extracted the zip file and copied folder "WebViewerExample" to the tomcat-webapps folder and renamed the folder to "birt_4.17". I started the tomcat and checked the results with the manager view and all was fine on my side.
> 
> ![grafik](https://private-user-images.githubusercontent.com/41593722/385777095-95f06640-32ca-4578-9da0-4e4c9b99b6ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1MDQ3OTUsIm5iZiI6MTczMTUwNDQ5NSwicGF0aCI6Ii80MTU5MzcyMi8zODU3NzcwOTUtOTVmMDY2NDAtMzJjYS00NTc4LTlkYTAtNGU0YzliOTliNmNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEzVDEzMjgxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5ZjJkMTY0ZjJkZTE3MjU0ZjQ1YzcyNTA2ZTA2YjMyNjIwMGI5YTEyZWFkODdiNjIwZjEzOTJhOTYzODcxMzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.TfHDa-hPw_DElI7-fQcSXLmgGiiOSDhbvYwg_owMs0c)
> 
> ![grafik](https://private-user-images.githubusercontent.com/41593722/385775755-913cbcf3-ae6f-486c-ab63-2db1be87aa6f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1MDQ3OTUsIm5iZiI6MTczMTUwNDQ5NSwicGF0aCI6Ii80MTU5MzcyMi8zODU3NzU3NTUtOTEzY2JjZjMtYWU2Zi00ODZjLWFiNjMtMmRiMWJlODdhYTZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEzVDEzMjgxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0M2E4YzJlMTAyNzQzNTExMzkyMGQ4NTAzZTExNjVjMmFhNzUxNzM5YTIwY2JjYTZhYjM5MDcwOTc0MzU5YzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.BHUi2ckq39MrdlM80e_56m37pIW44lJuIkfRVfk5QWM)
> 
> ![grafik](https://private-user-images.githubusercontent.com/41593722/385775855-08559464-c468-4949-b424-01e371c9e2c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1MDQ3OTUsIm5iZiI6MTczMTUwNDQ5NSwicGF0aCI6Ii80MTU5MzcyMi8zODU3NzU4NTUtMDg1NTk0NjQtYzQ2OC00OTQ5LWI0MjQtMDFlMzcxYzllMmMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEzVDEzMjgxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3Y2FhNWJlYzU0MjRjMzg3MzlkNTczZjQ3MjU3NTVjNmFiZTQ0MjVhMmM2ZmE1ODNlNTdkMzhhYmE1NGZmNGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.aX73TBTeCw0EGfVBTVVJv7Cgl2NMDH7XZuSMjAp2I-M)

I see, i will start over and test again, what java version is used?

**Comment by washaqq** [comment]
@speckyspooky i did start over with Tomcat version 9.0.88 same version as you tried.
but no, it didn't work i have same problem.

new logs; 
[catalina.2024-11-13.log](https://github.com/user-attachments/files/17733346/catalina.2024-11-13.log)
[commons-daemon.2024-11-13.log](https://github.com/user-attachments/files/17733347/commons-daemon.2024-11-13.log)
[host-manager.2024-11-13.log](https://github.com/user-attachments/files/17733348/host-manager.2024-11-13.log)
[localhost.2024-11-13.log](https://github.com/user-attachments/files/17733349/localhost.2024-11-13.log)
[localhost_access_log.2024-11-13.txt](https://github.com/user-attachments/files/17733350/localhost_access_log.2024-11-13.txt)
[manager.2024-11-13.log](https://github.com/user-attachments/files/17733351/manager.2024-11-13.log)
[service-install.log](https://github.com/user-attachments/files/17733352/service-install.log)
[tomcat9-stderr.2024-11-13.log](https://github.com/user-attachments/files/17733353/tomcat9-stderr.2024-11-13.log)
[tomcat9-stdout.2024-11-13.log](https://github.com/user-attachments/files/17733354/tomcat9-stdout.2024-11-13.log)

**Comment by claesrosell** [comment]
@washaqq you are using JavaSE-8, you need to use a much more recent version of Java. JavaSE-17 should work
![bild](https://github.com/user-attachments/assets/f3423fb1-33bb-4047-941c-bd2612df3369)

**Comment by washaqq** [comment]
> @washaqq you are using JavaSE-8, you need to use a much more recent version of Java. JavaSE-17 should work ![bild](https://private-user-images.githubusercontent.com/8941815/385787165-f3423fb1-33bb-4047-941c-bd2612df3369.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1MDY1MzQsIm5iZiI6MTczMTUwNjIzNCwicGF0aCI6Ii84OTQxODE1LzM4NTc4NzE2NS1mMzQyM2ZiMS0zM2JiLTQwNDctOTQxYy1iZDI2MTJkZjMzNjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTNUMTM1NzE0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDk0OTQyMTZmZjk0N2MyNmY5MWU3MGQzMzBkNGU5OTc1NzZiMmNiYjU2MTk0MzIyOTAzMzg1OTQ4OTBjODM5OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.0KsHFMfrO0ZrasHlBWjLFU_z3KfSpIwGltpLK7MHjN0)


Hi @claesrosell,
Thank you for helping, I tried more recent version jdk-21, it seems working;

![image](https://github.com/user-attachments/assets/1a0f1285-b167-40db-ad7f-adc34b7e6636)

Thank you.

**Comment by mendu1228** [comment]
Hi Wasaqq,

Please proceed with the following steps:

Download and install Java 17.

Download and install Tomcat 9.0.

During the Tomcat setup, ensure that the Java 17 installation path is correctly configured and pointed to by Tomcat.

Deploy the birt.war file (BIRT) to the Tomcat webapps directory.

Restart the Tomcat service.

After the restart, verify that the BIRT application is successfully deployed and running.
