### ISSUE TITLE
How to apply dataset filter expression while get parameter selection list?

### ISSUE THREAD

**Issue by chille716** [eclipse-birt/birt#1993]
Hello,  

i have a report design with a dataset and a filter expression like the following one:
![grafik](https://github.com/user-attachments/assets/82405fda-21d5-4f09-9f01-b44f599ee055)

This data set will be used as dynamic values source for a report parameter.  

My problem is now, that the filter expression will not apply, while fetching the values of the parameter with help of the java method: IGetParameterDefinitionTask#getSelectionList

This behavior was changed with version 4.8 and is already mentioned in https://github.com/eclipse-birt/birt/commit/e19c5f5c4f839ada0a5a0f2e16d22bfd00adc821#r39507859

Now my question: Is there any way to change the DataEngineFlowMode for this use case? Or is there another way to fetch the parameters, considering the filter expressions of a data set?

**Comment by speckyspooky** [comment]
Currently there is no configuration to change the behavior.
Which kind of dataset do you use? If you would use a sql-statement you can do it directly there.
But based on the screen it seems that you doesn't use sql.

**Comment by speckyspooky** [comment]
If we would add a configuration there it must be a kind of global parameter because it has an impact for all elements of a report.
And if it is the requirement so we it should work for all reports with the according configuration.
So we can talk about to add a global configuration for the JVM like `-Dbirt.driver.property.validation.excluded.drivers`.

But be aware it could be that you get in trouble with the topics of the discussion which cause the change.

**Comment by speckyspooky** [comment]
I understand. So it if I have time, I can spend time for research of it for BIRT 4.19.
The target would be to have a set- & get-method to set the "DataEngineFlowMode" which shall be accessible through the interface class.

**Comment by chille716** [comment]
This would be great. We only made the following changes locally... 
[diff.txt](https://github.com/user-attachments/files/18010917/diff.txt)
but as already mentioned, i'm not sure if this is a 100% solution.

**Comment by wimjongman** [comment]
@chille716 can you make a pull request?

**Comment by chille716** [comment]
@wimjongman yes, i will do it in the next few days.

**Comment by wimjongman** [comment]
> @wimjongman yes, i will do it in the next few days.

Thanks @chille716. In case you did not do it. Please sign the Eclipse Contributor Agreement. Make sure to use your github email when you create an Eclipse Account.  

https://www.eclipse.org/legal/eca/

![image](https://github.com/user-attachments/assets/697c43d9-8d62-478a-8a41-d3ca34ce41ea)

**Comment by merks** [comment]
FYI @wimjongman 

Note that one really ought to add `@since` comments when adding API...

**Comment by speckyspooky** [comment]
I can add them this evening.
