### ISSUE TITLE
Duplicate RotatedText plugin in all-in-one-designer

### ISSUE THREAD

**Issue by hvbtup** [eclipse-birt/birt#884]
The designer barks on startup something about a duplicate extension.
I'm pretty sure this is caused by the RotatedText tutorial. There are two versions of this plugin.
The first version is a very basic one with only static text, the other one is actually useful and allows dynamic text.
The first version should not be included.

**Comment by priytosh-tripathi** [comment]
Hi @hvbtup 

Looks like this issue has not been addressed for a while now. Can you provide some more relevant information on it so that I may try to find a fix! 
Thank you for your support!

**Comment by hvbtup** [comment]
I think it should be easy to fix it. There are two versions of the example code in the source code, both of them are using the same id. The first version should be excluded from the build - this will fix this issue.
It should be kept in the sources as an example to use if someone wants to see what is the minimum code necessary to create a custom item.

**Comment by priytosh-tripathi** [comment]
Hi @hvbtup ,

Thankyou for illustrating. Can you please assign this to me? I have tried fixing this here : https://github.com/eclipse/birt/pull/1191 , please suggest if that's what we're looking for or we need some more tuning to it. 

We can then proceed with a formal PR to merge once everything stands up to the standard. 

Thanks for your generous help!

**Comment by speckyspooky** [comment]
The topic is solved with PR #1191
