### ISSUE TITLE
Refused to set unsafe header "Connection"

### ISSUE THREAD

**Issue by krishnakittu** [eclipse-birt/birt#938]
Hi Team,

When we open any parameterized report upon click on submit , browser console shows this error. Tried on EDGE

![Capture1](https://user-images.githubusercontent.com/2696719/163514747-fa1b33b1-74fe-4da7-a5c5-50e705723a4b.PNG)

**Comment by wimjongman** [comment]
Note: https://stackoverflow.com/questions/7210507/ajax-post-error-refused-to-set-unsafe-header-connection

**Comment by speckyspooky** [comment]
I tested the latest BIRT 4.14 nightly built version with a report which has 1 parameter and I didn't get the issue with the latest browser version of Edge, FireForx & Chrome.

Therefore I will close the issue. If you have the message with your report and the latest BIRT-version again
the issue can be reopend. In this case please add a sample report where the effect can be reproduced.
