### ISSUE TITLE
Add a DENSE_RANK aggregate function (like in SQL)

### ISSUE THREAD

**Issue by hvbtup** [eclipse-birt/birt#981]
We have SUM, AVE, COUNT aggregate function etc. and RANK, but not DENSE_RANK.

The DENSE_RANK aggregate function often comes handy.

The important difference between DENSE_RANK and RANK is that if you have e.g. 4 rows with the following values (assuming they are already sorted:

     value       RANK    DENSE_RANK
     ABC         1         1
     ABC         1         1
     DEF         3         2
     GHI         4         3

DENSE_RANK can be used for "auto-numbering" whereas RANK leaves gaps in the numbers.

See #975 for an example where the function is simulated with scripting.

**Comment by hvbtup** [comment]
We are both Germans and our understanding of English seems somewhat incompatible 😃. Maybe you can just call me in Bochum, 0234 94375 14

**Comment by Markus-Elfring** [comment]
Direct communication (as it happened a moment ago) can trigger further desirable effects.
